{{$language := sdict
"english" (dict
    6 "No alliance? Type \"skip\""
    9 "Awesome! <@!> You've just received your Server Tag! Now proceed to <#>. <1/5>"
    10 "<@!> Enter your alliance tag here <2/5>"
    11 "This is cool! <@!> you now have an Alliance Tag! Continue and proceed to <#>. <2/5>"
    12 "<@!> type your Character Game Name over here! <3/5>"
    13 "Perfect! <@!> you've updated your display name to your Character Game Name! Two more steps, proceed to <#>. <3/5>"
    14 "<@!> select your in-game alliance rank. <4/5>"
    16 "Cannot add reaction to user who has blocked bot. Nickname updated"
    17 "Please input a 3-4 digit tag"
    18 "Please input a numeric tag"
    19 "Please input a 3-4 character alliance tag"
    20 "Please don't use special characters"
    21 "Please input a 3-15 character username"
)
"spanish" (dict
    6 "¿Sin alianza? Escribe \"skip\""
    9 "¡Impresionante! %%USER%% ¡Acabas de recibir tu etiqueta de servidor! Ahora procede a $$CANAL$$. <1/5>"
    10 "%%USER%% Introduce tu etiqueta de alianza aquí <2/5>"
    11 "¡Esto es genial! %%USER%% ¡ahora tienes una etiqueta de alianza! Continúe y pase a $$CHANNEL$$. <2/5>"
    12 "%%USER%% ¡escribe el nombre del juego de tu personaje aquí! <3/5>"
    13 "¡Perfecto! %%USER%% ¡Has actualizado tu nombre para mostrar al nombre del juego de tu personaje! Dos pasos más, continúa con $$CHANNEL$$. <3/5>"
    14 "%%USER%% selecciona tu rango de alianza en el juego. <4/5>"
    16 "No se puede agregar una reacción al usuario que ha bloqueado el bot. Apodo actualizado"
    17 "Ingrese una etiqueta de 3 a 4 dígitos"
    18 "Ingrese una etiqueta numérica"
    19 "Ingrese una etiqueta de alianza de 3-4 caracteres"
    20 "Por favor no utilices caracteres especiales"
    21 "Ingrese un nombre de usuario de 3 a 15 caracteres"
)
"french" (dict
    6 "Pas d'alliance ? Tapez \"skip\""
    9 "Génial! %%USER%% Vous venez de recevoir votre Server Tag ! Passez maintenant à $$CHANNEL$$. <1/5>"
    10 "%%USER%% Entrez votre tag d'alliance ici <2/5>"
    11 "C'est cool! %%USER%% vous avez maintenant un tag Alliance ! Continuez et passez à $$CHANNEL$$. <2/5>"
    12 "%%USER%% tapez le nom de votre jeu de personnage ici ! <3/5>"
    13 "Parfait! %%USER%% vous avez mis à jour votre nom d'affichage avec le nom de votre jeu de personnage ! Deux étapes supplémentaires, passez à $$CHANNEL$$. <3/5>"
    14 "%%USER%% sélectionnez votre rang d'alliance dans le jeu. <4/5>"
    16 "Impossible d'ajouter une réaction à l'utilisateur qui a bloqué le bot. Pseudonyme mis à jour"
    17 "Veuillez saisir une balise à 3-4 chiffres"
    18 "Veuillez saisir une balise numérique"
    19 "Veuillez saisir une balise d'alliance de 3 à 4 caractères"
    20 "Merci de ne pas utiliser de caractères spéciaux"
    21 "Veuillez saisir un nom d'utilisateur de 3 à 15 caractères"
)
"russian" (dict
    6 "Нет союза? Напишите \"skip\""
    9 "Потрясающий! %%USER%% Вы только что получили тег сервера! Теперь перейдите к $$CHANNEL$$. <1/5>"
    10 "%%USER%% Введите здесь тег вашего альянса <2/5>"
    11 "Это здорово! %%USER%% теперь у вас есть тег альянса! Продолжайте и перейдите к $$CHANNEL$$. <2/5>"
    12 "%%USER%% введите здесь свое игровое имя персонажа! <3/5>"
    13 "Идеальный! %%USER%% вы обновили отображаемое имя на игровое имя вашего персонажа! Еще два шага, переходим к $$CHANNEL$$. <3/5>"
    14 "%%USER%% выберите свой внутриигровой рейтинг альянса. <4/5>"
    16 "Невозможно добавить реакцию на пользователя, заблокировавшего бота. Псевдоним обновлен"
    17 "Введите тег из 3-4 цифр"
    18 "Пожалуйста, введите числовой тег"
    19 "Введите тег альянса из 3-4 символов"
    20 "Пожалуйста, не используйте специальные символы"
    21 "Пожалуйста, введите имя пользователя длиной от 3 до 15 символов"
)
"chinese" (dict
    6 " 没有联盟? 输入 \"skip\""
    9 "惊人的! %%USER%% 您刚刚收到您的服务器标签! 现在前往$$CHANNEL$$. <1/5>"
    10 "%%USER%% 在此输入您的联盟标签 <2/5>"
    11 "这很酷! %%USER%% 您现在拥有联盟标签! 继续并前往$$CHANNEL$$. <2/5>"
    12 "%%USER%% 在这里输入您的角色游戏名称! <3/5>"
    13 "完美的! %%USER%% 您已将您的显示名称更新为您的角色游戏名称! 再执行两步，继续$$CHANNEL$$! <3/5>"
    14 " %%USER%% 选择您的游戏内联盟等级. <4/5>"
    16 "无法向阻止机器人的用户添加反应. 昵称已更新"
    17 "请输入3-4位标签"
    18 "请输入数字标签"
    19 "请输入3-4个字符的联盟标签"
    20 "请不要使用特殊字符"
    21 "请输入3-15个字符的用户名"
)
"arabic" (dict
    6 "لا يوجد تحالف؟ اكتب \"skip\""
    9 "مذهل! %%USER%% لقد استلمت للتو علامة الخادم الخاصة بك! انتقل الآن إلى $$CHANNEL$$. <1/5>"
    10 "%%USER%% أدخل علامة التحالف الخاصة بك هنا <2/5>"
    11 "ان هذا رائع! %%USER%% لديك الآن علامة تحالف! تابع وانتقل إلى $$CHANNEL$$. <2/5>"
    12 "%%USER%% اكتب اسم لعبة الشخصية الخاصة بك هنا! <3/5>"
    13 "ممتاز! %%USER%% لقد قمت بتحديث اسم العرض الخاص بك إلى اسم لعبة الشخصية الخاصة بك! خطوتان أخريان، تابع إلى $$CHANNEL$$. <3/5>"
    14 "%%USER%% حدد رتبة تحالفك داخل اللعبة. <4/5>"
    16 "لا يمكن إضافة رد فعل للمستخدم الذي قام بحظر الروبوت. تم تحديث اللقب"
    17 "الرجاء إدخال علامة مكونة من 3-4 أرقام"
    18 "الرجاء إدخال علامة رقمية"
    19 "الرجاء إدخال علامة تحالف مكونة من 3-4 أحرف"
    20 "الرجاء عدم استخدام أحرف خاصة"
    21 "الرجاء إدخال اسم مستخدم مكون من 3 إلى 15 حرفًا"
)
"korean" (dict
    6 "얼라이언스가 없나요? \"skip\" 를 입력하세요."
    9 "엄청난! %%USER%% 방금 서버 태그를 받았습니다! 이제 $$CHANNEL$$로 이동하세요. <1/5>"
    10 "%%USER%% 여기에 동맹 태그를 입력하세요 <2/5>"
    11 "이것은 멋지다! %%USER%% 이제 동맹 태그를 가지게 되었습니다! 계속해서 $$CHANNEL$$로 이동하세요. <2/5>"
    12 "%%USER%% 여기에 캐릭터 게임 이름을 입력하세요! <3/5>"
    13 "완벽한! %%USER%% 표시 이름을 캐릭터 게임 이름으로 업데이트했습니다! 두 단계만 더 진행하면 $$CHANNEL$$로 이동합니다. <3/5>"
    14 "%%USER%% 게임 내 동맹 순위를 선택하세요. <4/5>"
    16 "봇을 차단한 사용자에게는 반응을 추가할 수 없습니다. 닉네임이 업데이트되었습니다."
    17 "3~4자리 태그를 입력해주세요."
    18 "숫자 태그를 입력해주세요."
    19 "연맹 태그를 3~4자로 입력해주세요."
    20 "특수문자는 사용하지 마세요."
    21 "3~15자의 사용자 이름을 입력하세요"

)
"german" (dict
    6 "Kein Bündnis? Geben Sie \"skip\" ein"
    9 "Eindrucksvoll! %%USER%% Sie haben gerade Ihr Server-Tag erhalten! Fahren Sie nun mit $$CHANNEL$$ fort. <1/5>"
    10 "%%USER%% Geben Sie hier Ihr Allianz-Tag ein <2/5>"
    11 "Das ist cool! %%USER%% Sie haben jetzt ein Allianz-Tag! Fahren Sie fort und fahren Sie mit $$CHANNEL$$ fort. <2/5>"
    12 "%%USER%% Geben Sie hier Ihren Charakter-Spielnamen ein! <3/5>"
    13 "Perfekt! %%USER%% Sie haben Ihren Anzeigenamen auf den Namen Ihres Charakterspiels aktualisiert! Zwei weitere Schritte, fahren Sie mit $$CHANNEL$$ fort. <3/5>"
    14 "%%USER%% wähle deinen Allianzrang im Spiel aus. <4/5"
    16 "Dem Benutzer, der den Bot blockiert hat, kann keine Reaktion hinzugefügt werden. Spitzname aktualisiert"
    17 "Bitte geben Sie ein 3-4-stelliges Tag ein"
    18 "Bitte geben Sie ein numerisches Tag ein"
    19 "Bitte geben Sie einen Allianz-Tag mit 3-4 Zeichen ein"
    20 "Bitte verwenden Sie keine Sonderzeichen"
    21 "Bitte geben Sie einen 3-15 Zeichen langen Benutzernamen ein"
)
"vietnamese" (dict
    6 "Không có liên minh? Gõ \"skip\""
    9 "Tuyệt vời! %%USER%% Bạn vừa nhận được Thẻ máy chủ của mình! Bây giờ hãy chuyển sang $$CHANNEL$$. <1/5>"
    10 "%%USER%% Nhập thẻ liên minh của bạn vào đây <2/5>"
    11 "Cái này hay đấy! %%USER%% bạn hiện có Thẻ Liên minh! Tiếp tục và tiến tới $$CHANNEL$$. <2/5>"
    12 "%%USER%% nhập Tên trò chơi nhân vật của bạn vào đây! <3/5>"
    13 "Hoàn hảo! %%USER%% bạn đã cập nhật tên hiển thị thành Tên trò chơi nhân vật của mình! Hai bước nữa, tiến tới $$CHANNEL$$. <3/5>"
    14 "%%USER%% chọn thứ hạng liên minh trong trò chơi của bạn. <4/5>"
    16 "Không thể thêm phản ứng cho người dùng đã chặn bot. Đã cập nhật biệt hiệu"
    17 "Vui lòng nhập thẻ 3-4 chữ số"
    18 "Vui lòng nhập thẻ số"
    19 "Vui lòng nhập thẻ liên minh 3-4 ký tự"
    20 "Vui lòng không sử dụng ký tự đặc biệt"
    21 "Vui lòng nhập tên người dùng 3-15 ký tự"
)
"japanese" (dict
    6 "同盟はありませんか？ \"skip\"ップ」と入力してください"
    9 " 素晴らしい！ %%USER%% サーバー タグを受け取りました。 $$CHANNEL$$ に進みます。 <1/5>"
    10 "%%USER%% ここに同盟タグを入力してください <2/5>"
    11 "これはカッコいい！ %%USER%% さんは同盟タグを獲得しました! 続行して $$CHANNEL$$ に進みます。 <2/5>"
    12 "%%USER%% ここにキャラクター ゲーム名を入力してください! <3/5>"
    13 "完璧！ %%USER%% 表示名をキャラクター ゲーム名に更新しました! さらに 2 つの手順を実行して、$$CHANNEL$$ に進みます。 <3/5>"
    14 "%%USER%% はゲーム内の同盟ランクを選択します。 <4/5>"
    16 "ボットをブロックしたユーザーにリアクションを追加することはできません。 ニックネームを更新しました"
    17 "3-4桁のタグを入力してください"
    18 "数字タグを入力してください"
    19 "3-4文字の同盟タグを入力してください"
    20 "特殊文字は使用しないでください"
    21 "3-15 文字のユーザー名を入力してください"
)
"turkish" (dict
    6 "İttifak yok mu? \"skip\" yazın"
    9 "Mükemmel! %%USER%% Sunucu Etiketinizi yeni aldınız! Şimdi $$CHANNEL$$'a ilerleyin. <1/5>"
    10 "%%USER%% İttifak etiketinizi buraya girin <2/5>"
    11 "Bu havalı! %%USER%% artık bir İttifak Etiketine sahipsiniz! Devam edin ve $$CHANNEL$$'a ilerleyin. <2/5>"
    12 "%%USER%% Karakter Oyunu Adınızı buraya yazın! <3/5>"
    13 "Mükemmel! %%USER%%, görünen adınızı Karakter Oyunu Adınızla güncellediniz! İki adım daha, $$CHANNEL$$'a ilerleyin. <3/5>"
    14 "%%USER%% oyun içi ittifak rütbenizi seçin. <4/5>"
    16 "Botu engelleyen kullanıcıya tepki eklenemez. Takma ad güncellendi"
    17 "Lütfen 3-4 haneli bir etiket girin"
    18 "Lütfen sayısal bir etiket girin"
    19 "Lütfen 3-4 karakterlik bir ittifak etiketi girin"
    20 "Lütfen özel karakterler kullanmayın"
    21 "Lütfen 3-15 karakterlik bir kullanıcı adı girin"
)
"portugese" (dict
    6 "Sem aliança? Digite \"skip\""
    9 "Incrível! %%USER%% Você acabou de receber sua etiqueta de servidor! Agora prossiga para $$CHANNEL$$. <1/5>"
    10 "%%USER%% Digite sua tag de aliança aqui <2/5>"
    11 "Isso é legal! %%USER%% agora você tem uma etiqueta de aliança! Continue e prossiga para $$CHANNEL$$. <2/5>"
    12 "%%USER%% digite o nome do jogo do seu personagem aqui! <3/5>"
    13 "Perfeito! %%USER%% você atualizou seu nome de exibição para o nome do jogo do seu personagem! Mais duas etapas, prossiga para $$CHANNEL$$. <3/5>"
    14 "%%USER%% selecione a classificação da sua aliança no jogo. <4/5>"
    16 "Não é possível adicionar reação ao usuário que bloqueou o bot. Apelido atualizado"
    17 "Insira uma etiqueta de 3 a 4 dígitos"
    18 "Por favor insira uma tag numérica"
    19 "Por favor, insira uma tag de aliança de 3 a 4 caracteres"
    20 "Por favor, não use caracteres especiais"
    21 "Insira um nome de usuário de 3 a 15 caracteres"
)
"malaysian" (dict
    6 "Tiada pakatan? Taip \"skip\""
    9 "Hebat! %%USER%% Anda baru sahaja menerima Teg Pelayan anda! Sekarang teruskan ke $$CHANNEL$$. <1/5>"
    10 "%%USER%% Masukkan teg pakatan anda di sini <2/5>"
    11 "Ini hebat! %%USER%% anda kini mempunyai Teg Perikatan! Teruskan dan teruskan ke $$CHANNEL$$. <2/5>"
    12 "%%USER%% taip Nama Permainan Watak anda di sini! <3/5>"
    13 "Sempurna! %%USER%% anda telah mengemas kini nama paparan anda kepada Nama Permainan Watak anda! Dua langkah lagi, teruskan ke $$CHANNEL$$. <3/5>"
    14 "%%USER%% pilih pangkat pakatan dalam permainan anda. <4/5>"
    16 "Tidak boleh menambah reaksi kepada pengguna yang telah menyekat bot. Nama samaran dikemas kini"
    17 "Sila masukkan teg 3-4 digit"
    18 "Sila masukkan teg angka"
    19 "Sila masukkan teg pakatan 3-4 aksara"
    20 "Tolong jangan gunakan aksara khas"
    21 "Sila masukkan nama pengguna 3-15 aksara"
)
"filipino" (dict
    6 "Walang alyansa? I-type ang \"skip\""
    9 "Galing! %%USER%% Natanggap mo lang ang iyong Server Tag! Ngayon magpatuloy sa $$CHANNEL$$. <1/5>"
    10 "%%USER%% Ilagay ang iyong alliance tag dito <2/5>"
    11 "Ito ay cool! %%USER%% mayroon ka na ngayong Alliance Tag! Magpatuloy at magpatuloy sa $$CHANNEL$$. <2/5>"
    12 "%%USER%% i-type ang iyong Character Game Name dito! <3/5>"
    13 "Perpekto! %%USER%% na-update mo ang iyong display name sa iyong Character Game Name! Dalawa pang hakbang, magpatuloy sa $$CHANNEL$$. <3/5>"
    14 "%%USER%% piliin ang iyong in-game alliance rank. <4/5>"
    16 "Hindi makapagdagdag ng reaksyon sa user na nag-block ng bot. Na-update ang palayaw"
    17 "Mangyaring maglagay ng 3-4 na digit na tag"
    18 "Mangyaring maglagay ng numeric na tag"
    19 "Mangyaring maglagay ng 3-4 na character na alliance tag"
    20 "Mangyaring huwag gumamit ng mga espesyal na character"
    21 "Mangyaring maglagay ng 3-15 character na username"
)
"ukranian" (dict
    6 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"indonesian" (dict
    6 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"greek" (dict
    6 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"dutch" (dict
    6 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"italian" (dict
    6 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"romanian" (dict
    6 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"danish" (dict
    6 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"polish" (dict
    6 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"hebrew" (dict
    6 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
}}