{{$language := sdict
"english" (dict
	1 "No alliance? Type \"skip\""
	2 "Awesome! <@!> You've just received your Server Tag! Now proceed to <#> <1/5>"
	3 "<@!> Enter your alliance tag here <2/5>"
	4 "This is cool! <@!> you now have an Alliance Tag! Continue and proceed to <#> <2/5>"
	5 "<@!> type your Character Game Name over here! <3/5>"
	6 "Perfect! <@!> you've updated your display name to your Character Game Name! Two more steps, proceed to <#> <3/5>"
	7 "<@!> select your in-game alliance rank <4/5>"
	8 "Cannot add reaction to user who has blocked bot. Nickname updated"
	9 "Please input a 3-4 digit tag"
	10 "Please input a numeric tag"
	11 "Please input a 3-4 character alliance tag"
	12 "Please don't use special characters"
	13 "Please input a 3-15 character username"
)
"spanish" (dict
	1 "¿Sin alianza? Escribe \"skip\""
	2 "¡Impresionante! <@!> ¡Acabas de recibir tu etiqueta de servidor! Ahora procede a $$CANAL$$ <1/5>"
	3 "<@!> Introduce tu etiqueta de alianza aquí <2/5>"
	4 "¡Esto es genial! <@!> ¡ahora tienes una etiqueta de alianza! Continúe y pase a $$CHANNEL$$ <2/5>"
	5 "<@!> ¡escribe el nombre del juego de tu personaje aquí! <3/5>"
	6 "¡Perfecto! <@!> ¡Has actualizado tu nombre para mostrar al nombre del juego de tu personaje! Dos pasos más, continúa con $$CHANNEL$$ <3/5>"
	7 "<@!> selecciona tu rango de alianza en el juego <4/5>"
	8 "No se puede agregar una reacción al usuario que ha bloqueado el bot. Apodo actualizado"
	9 "Ingrese una etiqueta de 3 a 4 dígitos"
	10 "Ingrese una etiqueta numérica"
	11 "Ingrese una etiqueta de alianza de 3-4 caracteres"
	12 "Por favor no utilices caracteres especiales"
	13 "Ingrese un nombre de usuario de 3 a 15 caracteres"
)
"french" (dict
	1 "Pas d'alliance ? Tapez \"skip\""
	2 "Génial! <@!> Vous venez de recevoir votre Server Tag ! Passez maintenant à $$CHANNEL$$ <1/5>"
	3 "<@!> Entrez votre tag d'alliance ici <2/5>"
	4 "C'est cool! <@!> vous avez maintenant un tag Alliance ! Continuez et passez à $$CHANNEL$$ <2/5>"
	5 "<@!> tapez le nom de votre jeu de personnage ici ! <3/5>"
	6 "Parfait! <@!> vous avez mis à jour votre nom d'affichage avec le nom de votre jeu de personnage ! Deux étapes supplémentaires, passez à $$CHANNEL$$ <3/5>"
	7 "<@!> sélectionnez votre rang d'alliance dans le jeu <4/5>"
	8 "Impossible d'ajouter une réaction à l'utilisateur qui a bloqué le bot. Pseudonyme mis à jour"
	9 "Veuillez saisir une balise à 3-4 chiffres"
	10 "Veuillez saisir une balise numérique"
	11 "Veuillez saisir une balise d'alliance de 3 à 4 caractères"
	12 "Merci de ne pas utiliser de caractères spéciaux"
	13 "Veuillez saisir un nom d'utilisateur de 3 à 15 caractères"
)
"russian" (dict
	1 "Нет союза? Напишите \"skip\""
	2 "Потрясающий! <@!> Вы только что получили тег сервера! Теперь перейдите к $$CHANNEL$$ <1/5>"
	3 "<@!> Введите здесь тег вашего альянса <2/5>"
	4 "Это здорово! <@!> теперь у вас есть тег альянса! Продолжайте и перейдите к $$CHANNEL$$ <2/5>"
	5 "<@!> введите здесь свое игровое имя персонажа! <3/5>"
	6 "Идеальный! <@!> вы обновили отображаемое имя на игровое имя вашего персонажа! Еще два шага, переходим к $$CHANNEL$$ <3/5>"
	7 "<@!> выберите свой внутриигровой рейтинг альянса <4/5>"
	8 "Невозможно добавить реакцию на пользователя, заблокировавшего бота. Псевдоним обновлен"
	9 "Введите тег из 3-4 цифр"
	10 "Пожалуйста, введите числовой тег"
	11 "Введите тег альянса из 3-4 символов"
	12 "Пожалуйста, не используйте специальные символы"
	13 "Пожалуйста, введите имя пользователя длиной от 3 до 15 символов"
)
"chinese" (dict
	1 " 没有联盟? 输入 \"skip\""
	2 "惊人的! <@!> 您刚刚收到您的服务器标签! 现在前往$$CHANNEL$$ <1/5>"
	3 "<@!> 在此输入您的联盟标签 <2/5>"
	4 "这很酷! <@!> 您现在拥有联盟标签! 继续并前往$$CHANNEL$$ <2/5>"
	5 "<@!> 在这里输入您的角色游戏名称! <3/5>"
	6 "完美的! <@!> 您已将您的显示名称更新为您的角色游戏名称! 再执行两步，继续$$CHANNEL$$! <3/5>"
	7 " <@!> 选择您的游戏内联盟等级 <4/5>"
	8 "无法向阻止机器人的用户添加反应. 昵称已更新"
	9 "请输入3-4位标签"
	10 "请输入数字标签"
	11 "请输入3-4个字符的联盟标签"
	12 "请不要使用特殊字符"
	13 "请输入3-15个字符的用户名"
)
"arabic" (dict
	1 "لا يوجد تحالف؟ اكتب \"skip\""
	2 "مذهل! <@!> لقد استلمت للتو علامة الخادم الخاصة بك! انتقل الآن إلى $$CHANNEL$$ <1/5>"
	3 "<@!> أدخل علامة التحالف الخاصة بك هنا <2/5>"
	4 "ان هذا رائع! <@!> لديك الآن علامة تحالف! تابع وانتقل إلى $$CHANNEL$$ <2/5>"
	5 "<@!> اكتب اسم لعبة الشخصية الخاصة بك هنا! <3/5>"
	6 "ممتاز! <@!> لقد قمت بتحديث اسم العرض الخاص بك إلى اسم لعبة الشخصية الخاصة بك! خطوتان أخريان، تابع إلى $$CHANNEL$$ <3/5>"
	7 "<@!> حدد رتبة تحالفك داخل اللعبة. <4/5>"
	8 "لا يمكن إضافة رد فعل للمستخدم الذي قام بحظر الروبوت. تم تحديث اللقب"
	9 "الرجاء إدخال علامة مكونة من 3-4 أرقام"
	10 "الرجاء إدخال علامة رقمية"
	11 "الرجاء إدخال علامة تحالف مكونة من 3-4 أحرف"
	12 "الرجاء عدم استخدام أحرف خاصة"
	13 "الرجاء إدخال اسم مستخدم مكون من 3 إلى 15 حرفًا"
)
"korean" (dict
	1 "얼라이언스가 없나요? \"skip\" 를 입력하세요."
	2 "엄청난! <@!> 방금 서버 태그를 받았습니다! 이제 $$CHANNEL$$로 이동하세요 <1/5>"
	3 "<@!> 여기에 동맹 태그를 입력하세요 <2/5>"
	4 "이것은 멋지다! <@!> 이제 동맹 태그를 가지게 되었습니다! 계속해서 $$CHANNEL$$로 이동하세요 <2/5>"
	5 "<@!> 여기에 캐릭터 게임 이름을 입력하세요! <3/5>"
	6 "완벽한! <@!> 표시 이름을 캐릭터 게임 이름으로 업데이트했습니다! 두 단계만 더 진행하면 $$CHANNEL$$로 이동합니다 <3/5>"
	7 "<@!> 게임 내 동맹 순위를 선택하세요 <4/5>"
	8 "봇을 차단한 사용자에게는 반응을 추가할 수 없습니다. 닉네임이 업데이트되었습니다"
	9 "3~4자리 태그를 입력해주세요"
	10 "숫자 태그를 입력해주세요"
	11 "연맹 태그를 3~4자로 입력해주세요"
	12 "특수문자는 사용하지 마세요"
	13 "3~15자의 사용자 이름을 입력하세요"

)
"german" (dict
	1 "Kein Bündnis? Geben Sie \"skip\" ein"
	2 "Eindrucksvoll! <@!> Sie haben gerade Ihr Server-Tag erhalten! Fahren Sie nun mit $$CHANNEL$$ fort\ <1/5>"
	3 "<@!> Geben Sie hier Ihr Allianz-Tag ein <2/5>"
	4 "Das ist cool! <@!> Sie haben jetzt ein Allianz-Tag! Fahren Sie fort und fahren Sie mit $$CHANNEL$$ fort <2/5>"
	5 "<@!> Geben Sie hier Ihren Charakter-Spielnamen ein! <3/5>"
	6 "Perfekt! <@!> Sie haben Ihren Anzeigenamen auf den Namen Ihres Charakterspiels aktualisiert! Zwei weitere Schritte, fahren Sie mit $$CHANNEL$$ fort <3/5>"
	7 "<@!> wähle deinen Allianzrang im Spiel aus <4/5"
	8 "Dem Benutzer, der den Bot blockiert hat, kann keine Reaktion hinzugefügt werden. Spitzname aktualisiert"
	9 "Bitte geben Sie ein 3-4-stelliges Tag ein"
	10 "Bitte geben Sie ein numerisches Tag ein"
	11 "Bitte geben Sie einen Allianz-Tag mit 3-4 Zeichen ein"
	12 "Bitte verwenden Sie keine Sonderzeichen"
	13 "Bitte geben Sie einen 3-15 Zeichen langen Benutzernamen ein"
)
"vietnamese" (dict
	1 "Không có liên minh? Gõ \"skip\""
	2 "Tuyệt vời! <@!> Bạn vừa nhận được Thẻ máy chủ của mình! Bây giờ hãy chuyển sang $$CHANNEL$$ <1/5>"
	3 "<@!> Nhập thẻ liên minh của bạn vào đây <2/5>"
	4 "Cái này hay đấy! <@!> bạn hiện có Thẻ Liên minh! Tiếp tục và tiến tới $$CHANNEL$$ <2/5>"
	5 "<@!> nhập Tên trò chơi nhân vật của bạn vào đây! <3/5>"
	6 "Hoàn hảo! <@!> bạn đã cập nhật tên hiển thị thành Tên trò chơi nhân vật của mình! Hai bước nữa, tiến tới $$CHANNEL$$ <3/5>"
	7 "<@!> chọn thứ hạng liên minh trong trò chơi của bạn <4/5>"
	8 "Không thể thêm phản ứng cho người dùng đã chặn bot. Đã cập nhật biệt hiệu"
	9 "Vui lòng nhập thẻ 3-4 chữ số"
	10 "Vui lòng nhập thẻ số"
	11 "Vui lòng nhập thẻ liên minh 3-4 ký tự"
	12 "Vui lòng không sử dụng ký tự đặc biệt"
	13 "Vui lòng nhập tên người dùng 3-15 ký tự"
)
"japanese" (dict
	1 "同盟はありませんか？ \"skip\"ップ」と入力してください"
	2 " 素晴らしい！ <@!> サーバー タグを受け取りました。 $$CHANNEL$$ に進みます <1/5>"
	3 "<@!> ここに同盟タグを入力してください <2/5>"
	4 "これはカッコいい！ <@!> さんは同盟タグを獲得しました! 続行して $$CHANNEL$$ に進みます <2/5>"
	5 "<@!> ここにキャラクター ゲーム名を入力してください! <3/5>"
	6 "完璧！ <@!> 表示名をキャラクター ゲーム名に更新しました! さらに 2 つの手順を実行して、$$CHANNEL$$ に進みます <3/5>"
	7 "<@!> はゲーム内の同盟ランクを選択します <4/5>"
	8 "ボットをブロックしたユーザーにリアクションを追加することはできません。 ニックネームを更新しました"
	9 "3-4桁のタグを入力してください"
	10 "数字タグを入力してください"
	11 "3-4文字の同盟タグを入力してください"
	12 "特殊文字は使用しないでください"
	13 "3-15 文字のユーザー名を入力してください"
)
"turkish" (dict
	1 "İttifak yok mu? \"skip\" yazın"
	2 "Mükemmel! <@!> Sunucu Etiketinizi yeni aldınız! Şimdi $$CHANNEL$$'a ilerleyin <1/5>"
	3 "<@!> İttifak etiketinizi buraya girin <2/5>"
	4 "Bu havalı! <@!> artık bir İttifak Etiketine sahipsiniz! Devam edin ve $$CHANNEL$$'a ilerleyin <2/5>"
	5 "<@!> Karakter Oyunu Adınızı buraya yazın! <3/5>"
	6 "Mükemmel! <@!>, görünen adınızı Karakter Oyunu Adınızla güncellediniz! İki adım daha, $$CHANNEL$$'a ilerleyin <3/5>"
	7 "<@!> oyun içi ittifak rütbenizi seçin <4/5>"
	8 "Botu engelleyen kullanıcıya tepki eklenemez. Takma ad güncellendi"
	9 "Lütfen 3-4 haneli bir etiket girin"
	10 "Lütfen sayısal bir etiket girin"
	11 "Lütfen 3-4 karakterlik bir ittifak etiketi girin"
	12 "Lütfen özel karakterler kullanmayın"
	13 "Lütfen 3-15 karakterlik bir kullanıcı adı girin"
)
"portugese" (dict
	1 "Sem aliança? Digite \"skip\""
	2 "Incrível! <@!> Você acabou de receber sua etiqueta de servidor! Agora prossiga para $$CHANNEL$$ <1/5>"
	3 "<@!> Digite sua tag de aliança aqui <2/5>"
	4 "Isso é legal! <@!> agora você tem uma etiqueta de aliança! Continue e prossiga para $$CHANNEL$$ <2/5>"
	5 "<@!> digite o nome do jogo do seu personagem aqui! <3/5>"
	6 "Perfeito! <@!> você atualizou seu nome de exibição para o nome do jogo do seu personagem! Mais duas etapas, prossiga para $$CHANNEL$$ <3/5>"
	7 "<@!> selecione a classificação da sua aliança no jogo. <4/5>"
	8 "Não é possível adicionar reação ao usuário que bloqueou o bot. Apelido atualizado"
	9 "Insira uma etiqueta de 3 a 4 dígitos"
	10 "Por favor insira uma tag numérica"
	11 "Por favor, insira uma tag de aliança de 3 a 4 caracteres"
	12 "Por favor, não use caracteres especiais"
	13 "Insira um nome de usuário de 3 a 15 caracteres"
)
"malaysian" (dict
	1 "Tiada pakatan? Taip \"skip\""
	2 "Hebat! <@!> Anda baru sahaja menerima Teg Pelayan anda! Sekarang teruskan ke $$CHANNEL$$ <1/5>"
	3 "<@!> Masukkan teg pakatan anda di sini <2/5>"
	4 "Ini hebat! <@!> anda kini mempunyai Teg Perikatan! Teruskan dan teruskan ke $$CHANNEL$$ <2/5>"
	5 "<@!> taip Nama Permainan Watak anda di sini! <3/5>"
	6 "Sempurna! <@!> anda telah mengemas kini nama paparan anda kepada Nama Permainan Watak anda! Dua langkah lagi, teruskan ke $$CHANNEL$$ <3/5>"
	7 "<@!> pilih pangkat pakatan dalam permainan anda <4/5>"
	8 "Tidak boleh menambah reaksi kepada pengguna yang telah menyekat bot. Nama samaran dikemas kini"
	9 "Sila masukkan teg 3-4 digit"
	10 "Sila masukkan teg angka"
	11 "Sila masukkan teg pakatan 3-4 aksara"
	12 "Tolong jangan gunakan aksara khas"
	13 "Sila masukkan nama pengguna 3-15 aksara"
)
"filipino" (dict
	1 "Walang alyansa? I-type ang \"skip\""
	2 "Galing! <@!> Natanggap mo lang ang iyong Server Tag! Ngayon magpatuloy sa $$CHANNEL$$ <1/5>"
	3 "<@!> Ilagay ang iyong alliance tag dito <2/5>"
	4 "Ito ay cool! <@!> mayroon ka na ngayong Alliance Tag! Magpatuloy at magpatuloy sa $$CHANNEL$$ <2/5>"
	5 "<@!> i-type ang iyong Character Game Name dito! <3/5>"
	6 "Perpekto! <@!> na-update mo ang iyong display name sa iyong Character Game Name! Dalawa pang hakbang, magpatuloy sa $$CHANNEL$$ <3/5>"
	7 "<@!> piliin ang iyong in-game alliance rank <4/5>"
	8 "Hindi makapagdagdag ng reaksyon sa user na nag-block ng bot. Na-update ang palayaw"
	9 "Mangyaring maglagay ng 3-4 na digit na tag"
	10 "Mangyaring maglagay ng numeric na tag"
	11 "Mangyaring maglagay ng 3-4 na character na alliance tag"
	12 "Mangyaring huwag gumamit ng mga espesyal na character"
	13 "Mangyaring maglagay ng 3-15 character na username"
)
"ukranian" (dict
	1 "Немає альянсу? Введіть \"skip\""
	2 "Чудово! <@!> Ви щойно отримали тег сервера! Тепер перейдіть до $$CHANNEL$$ <1/5>"
	3 "<@!> Введіть свій тег альянсу тут <2/5>"
	4 "Це круто! <@!> тепер у вас є тег Альянсу! Продовжте та перейдіть до $$CHANNEL$$ <2/5>"
	5 "- <@!> введіть тут своє ім'я гри персонажа! <3/5>"
	6 "Ідеально! <@!> ви оновили своє відображуване ім’я на ім’я гри персонажів! Ще два кроки, перейдіть до $$CHANNEL$$ <3/5>"
	7 "<@!> виберіть ранг вашого альянсу в грі <4/5>"
	8 "Неможливо додати реакцію на користувача, який заблокував бота. Псевдонім оновлено"
	9 "Будь ласка, введіть тег із 3-4 цифр"
	10 "Будь ласка, введіть числовий тег"
	11 "Будь ласка, введіть тег альянсу з 3-4 символів"
	12 "Будь ласка, не використовуйте спеціальні символи"
	13 "Будь ласка, введіть ім'я користувача з 3-15 символів"
)
"indonesian" (dict
	1 "Tidak ada aliansi? Ketik \"skip\""
	2 "Luar biasa! <@!> Anda baru saja menerima Tag Server Anda! Sekarang lanjutkan ke $$CHANNEL$$ <1/5>"
	3 "<@!> Masukkan tag aliansi Anda di sini <2/5>"
	4 "Ini keren! <@!> Anda sekarang memiliki Tag Aliansi! Lanjutkan dan lanjutkan ke $$CHANNEL$$ <2/5>"
	5 "<@!> ketik Nama Karakter Game Anda di sini! <3/5>"    
	6 "Sempurna! <@!> Anda telah memperbarui nama tampilan Anda menjadi Nama Permainan Karakter Anda! Dua langkah lagi, lanjutkan ke $$CHANNEL$$ <3/5>"
	7 "<@!> pilih peringkat aliansi dalam game Anda. <4/5>"    
	8 "Tidak dapat menambahkan reaksi kepada pengguna yang telah memblokir bot. Nama panggilan diperbarui"
	9 "Silakan masukan tag 3-4 digit"
	10 "Silakan masukkan tag numerik"
	11 "Silakan masukkan tag aliansi 3-4 karakter"
	12 "Tolong jangan gunakan karakter khusus"
	13 "Silakan masukan nama pengguna 3-15 karakter"    
)
"greek" (dict
	1 "Δεν υπάρχει συμμαχία; Πληκτρολογήστε \"skip\""
	2 "Φοβερό! <@!> Μόλις λάβατε την ετικέτα διακομιστή σας! Τώρα προχωρήστε στο $$CHANNEL$$ <1/5>"
	3 "<@!> Εισαγάγετε την ετικέτα συμμαχίας σας εδώ <2/5>"    
	4 "Αυτό είναι ωραίο! <@!> έχετε τώρα Ετικέτα Συμμαχίας! Συνεχίστε και προχωρήστε στο $$CHANNEL$$ <2/5>"
	5 "<@!> πληκτρολογήστε το όνομα του παιχνιδιού χαρακτήρων εδώ! <3/5>"	
	6 "Τέλειος! <@!> έχετε ενημερώσει το εμφανιζόμενο όνομά σας στο όνομα του παιχνιδιού χαρακτήρων! Δύο ακόμη βήματα, προχωρήστε στο $$CHANNEL$$ <3/5>"
	7 "<@!> επιλέξτε την κατάταξη συμμαχίας στο παιχνίδι <4/5>"	
	8 "Δεν είναι δυνατή η προσθήκη αντίδρασης σε χρήστη που έχει αποκλείσει το bot. Το ψευδώνυμο ενημερώθηκε"
	9 "Εισαγάγετε μια ετικέτα 3-4 ψηφίων"
	10 "Εισαγάγετε μια αριθμητική ετικέτα"
	11 "Εισαγάγετε μια ετικέτα συμμαχίας 3-4 χαρακτήρων"
	12 "Μην χρησιμοποιείτε ειδικούς χαρακτήρες"
	13 "Εισαγάγετε ένα όνομα χρήστη 3-15 χαρακτήρων"
)
"dutch" (dict
	1 "Geen alliantie? Typ \"skip\""
	2 "Geweldig! <@!> U heeft zojuist uw servertag ontvangen! Ga nu verder naar $$CHANNEL$$ <1/5>"
	3 "<@!> Voer hier uw alliantietag in <2/5>"
	4 "Dit is cool! <@!> je hebt nu een alliantietag! Ga verder en ga naar $$CHANNEL$$ <2/5>"
	5 "<@!> typ hier de naam van je personagespel! <3/5>"	
	6 "Perfect! <@!> je hebt je weergavenaam bijgewerkt naar je personagespelnaam! Nog twee stappen, ga verder naar $$CHANNEL$$ <3/5>"
	7 "<@!> selecteer je in-game alliantierang <4/5>"	
	8 "Kan geen reactie toevoegen aan de gebruiker die de bot heeft geblokkeerd. Bijnaam bijgewerkt"
	9 "Voer een tag van 3 tot 4 cijfers in"
	10 "Voer een numerieke tag in"
	11 "Voer een alliantietag van 3 tot 4 tekens in"
	12 "Gebruik geen speciale tekens"
	13 "Voer een gebruikersnaam van 3-15 tekens in"	
)
"italian" (dict
	1 "Nessuna alleanza? Digita \"skip\""
	2 "Eccezionale! <@!> Hai appena ricevuto il tuo Tag Server! Ora procedi a $$CHANNEL$$ <1/5>"
	3 "<@!> Inserisci qui il tag della tua alleanza <2/5>"	
	4 "È fantastico! <@!> ora hai un tag dell'Alleanza! Continua e procedi con $$CHANNEL$$ <2/5>"
	5 "<@!> digita il nome del gioco del tuo personaggio qui! <3/5>"
	6 "Perfetto! <@!> hai aggiornato il tuo nome visualizzato con il nome del gioco del tuo personaggio! Altri due passaggi, procedi a $$CHANNEL$$ <3/5>"
	7 "<@!> seleziona il grado della tua alleanza nel gioco <4/5>"
	8 "Impossibile aggiungere una reazione all'utente che ha bloccato il bot. Soprannome aggiornato"
	9 "Inserisci un tag di 3-4 cifre"
	10 "Inserisci un tag numerico"
	11 "Inserisci un tag di alleanza di 3-4 caratteri"
	12 "Per favore non usare caratteri speciali"
	13 "Inserisci un nome utente di 3-15 caratteri"	
)
"romanian" (dict
	1 "Fără alianță? Tastați \"skip\""
	2 "Minunat! <@!> Tocmai ați primit eticheta de server! Acum treceți la $$CHANNEL$$ <1/5>"
	3 "<@!> Introdu eticheta de alianță aici <2/5>"
	4 "Aceasta este cool! <@!> acum aveți o etichetă de alianță! Continuați și treceți la $$CHANNEL$$ <2/5>"
	5 "<@!> introduceți numele jocului dvs. de personaj aici! <3/5>"
	6 "Perfect! <@!> ți-ai actualizat numele afișat la Numele jocului de personaj! Încă doi pași, treceți la $$CHANNEL$$ <3/5>"
	7 "<@!> selectează rangul alianței în joc <4/5>"
	8 "Nu se poate adăuga reacție utilizatorului care a blocat bot. Pseudomul a fost actualizat"
	9 "Vă rugăm să introduceți o etichetă de 3-4 cifre"
	10 "Vă rugăm să introduceți o etichetă "
	11 "Vă rugăm să introduceți o etichetă de alianță de 3-4 caractere"
	12 "Vă rugăm să nu folosiți caractere speciale"
	13 "Vă rugăm să introduceți un nume de utilizator de 3-15 caractere"	
)
"danish" (dict
	1 "Ingen alliance? Skriv \"skip\""
	2 "Fantastisk! <@!> Du har lige modtaget dit server-tag! Fortsæt nu til $$CHANNEL$$ <1/5>"
	3 "<@!> Indtast dit alliance-tag her <2/5>"
	4 "Det her er sejt! <@!> du har nu et Alliance-tag! Fortsæt og fortsæt til $$CHANNEL$$ <2/5>"
	5 " <@!> skriv dit karakterspils navn her! <3/5>"
	6 "Perfekt! <@!> du har opdateret dit viste navn til dit karakterspilsnavn! To trin mere, fortsæt til $$CHANNEL$$ <3/5>"
	7 "<@!> vælg din alliancerangering i spillet <4/5>"
	8 "Kan ikke tilføje reaktion til bruger, der har blokeret bot. Kaldenavnet er opdateret"
	9 "Indtast venligst et 3-4-cifret tag"
	10 "Indtast venligst et numerisk tag"
	11 "Indtast venligst et alliancemærke på 3-4 tegn"
	12 "Brug venligst ikke specialtegn"
	13 "Indtast venligst et brugernavn på 3-15 tegn"
)
"polish" (dict
	1 "Brak sojuszu? Wpisz \"skip\""
	2 "Wspaniały! <@!> Właśnie otrzymałeś swój tag serwera! Teraz przejdź do $$CHANNEL$$ <1/5>"
	3 "<@!> Wpisz tutaj swój tag sojuszu <2/5>"
	4 "To jest fajne! <@!> masz teraz tag sojuszu! Kontynuuj i przejdź do $$CHANNEL$$ <2/5>"
	5 "<@!> wpisz tutaj swoją nazwę gry postaci! <3/5>"
	6 "Doskonały! <@!> zaktualizowałeś swoją nazwę wyświetlaną do nazwy gry postaci! Jeszcze dwa kroki i przejdź do $$CHANNEL$$ <3/5>"
	7 "<@!> wybierz swoją rangę sojuszu w grze <4/5>"
	8 "Nie można dodać reakcji do użytkownika, który zablokował bota. Pseudonim zaktualizowany"
	9 "Proszę wprowadzić 3-4 cyfrowy znacznik"
	10 "Proszę wprowadzić znacznik numeryczny"
	11 "Proszę wprowadzić tag sojuszu składający się z 3-4 znaków"
	12 "Proszę nie używać znaków specjalnych"
	13 "Wprowadź nazwę użytkownika zawierającą od 3 do 15 znaków"
)
"hebrew" (dict
	1 "אין ברית? הקלד \"skip\""
	2 "מדהים! <@!> זה עתה קיבלת את תג השרת שלך! כעת המשך ל-$$CHANNEL$$ <1/5>"
	3 "<@!> הזן את תג הברית שלך כאן <2/5>"
	4 "זה מגניב! <@!> יש לך כעת תג ברית! המשך והמשיך אל $$CHANNEL$$ <2/5>"
	5 "<@!> הקלד את שם משחק הדמות שלך כאן! <3/5>"
	6 "מושלם! <@!> עדכנת את שם התצוגה שלך לשם משחק הדמות שלך! שני שלבים נוספים, המשך אל $$CHANNEL$$ <3/5>"
	7 "<@!> בחר את דירוג הברית שלך במשחק. <4/5>"
	8 "לא ניתן להוסיף תגובה למשתמש שחסם בוט. הכינוי עודכן"
	9 "נא להזין תג בן 3-4 ספרות"
	10 "נא להזין תג מספרי"
	11 "אנא הזן תג ברית בן 3-4 תווים"
	12 "נא לא להשתמש בתווים מיוחדים"
	13 "נא להזין שם משתמש בן 3-15 תווים"
)
}}