{{$language := sdict
"english" (dict
    1 "Step 1/5: Type your Server Number ####"
    2 "Click <#> to proceed in verification"
    3 "This is STAMPED to the bottom of the channel!"
    4 "Step 2/5: Type your Alliance Tag ####"
    5 "Click <#> to proceed in verification"
    6 "No alliance? Type \"skip\""
    7 "Step 3/5: Type your game name to proceed"
    8 "Click <#> to proceed in verification"
    9 "Awesome! <@!> You've just received your Server Tag! Now proceed to <#>. <1/5>"
    10 "<@!> Enter your alliance tag here <2/5>"
    11 "This is cool! <@!> you now have an Alliance Tag! Continue and proceed to <#>. <2/5>"
    12 "<@!> type your Character Game Name over here! <3/5>"
    13 "Perfect! <@!> you've updated your display name to your Character Game Name! Two more steps, proceed to <#>. <3/5>"
    14 "<@!> select your in-game alliance rank. <4/5>"
    15 "Welcome to"
    16 "Cannot add reaction to user who has blocked bot. Nickname updated"
    17 "Please input a 3-4 digit tag"
    18 "Please input a numeric tag"
    19 "Please input a 3-4 character alliance tag"
    20 "Please don't use special characters"
    21 "Please input a 3-15 character username"
)
"spanish" (dict
    1 "Paso 1/5: Escriba su número de servidor ####"
    2 "Haga clic en <#> para continuar con la verificación"
    3 "¡Esto está ESTAMPADO al final del canal!"
    4 "Paso 2/5: Escribe tu etiqueta de alianza ####"
    5 "Haz clic en <#> para continuar con la verificación"
    6 "¿Sin alianza? Escribe \"skip\""
    7 "Paso 3/5: escribe el nombre de tu juego para continuar"
    8 "Haga clic en <#> para continuar con la verificación"
    9 "¡Impresionante! %%USER%% ¡Acabas de recibir tu etiqueta de servidor! Ahora procede a $$CANAL$$. <1/5>"
    10 "%%USER%% Introduce tu etiqueta de alianza aquí <2/5>"
    11 "¡Esto es genial! %%USER%% ¡ahora tienes una etiqueta de alianza! Continúe y pase a $$CHANNEL$$. <2/5>"
    12 "%%USER%% ¡escribe el nombre del juego de tu personaje aquí! <3/5>"
    13 "¡Perfecto! %%USER%% ¡Has actualizado tu nombre para mostrar al nombre del juego de tu personaje! Dos pasos más, continúa con $$CHANNEL$$. <3/5>"
    14 "%%USER%% selecciona tu rango de alianza en el juego. <4/5>"
    15 "Bienvenido a"
    16 "No se puede agregar una reacción al usuario que ha bloqueado el bot. Apodo actualizado"
    17 "Ingrese una etiqueta de 3 a 4 dígitos"
    18 "Ingrese una etiqueta numérica"
    19 "Ingrese una etiqueta de alianza de 3-4 caracteres"
    20 "Por favor no utilices caracteres especiales"
    21 "Ingrese un nombre de usuario de 3 a 15 caracteres"
)
"french" (dict
    1 "Étape 1/5 : Tapez votre numéro de serveur ####"
    2 "Cliquez sur ⁠$$🏰-alliance-only$$ pour procéder à la vérification"
    3 "Ceci est ESTAMPILLÉ au bas de la chaîne !"
    4 "Etape 2/5 : Tapez votre Tag Alliance ####"
    5 "Cliquez sur $$⁠🎮-game-name-only$$ pour procéder à la vérification"
    6 "Pas d'alliance ? Tapez \"skip\""
    7 "Étape 3/5 : Tapez le nom de votre jeu pour continuer"
    8 "Cliquez sur ⁠$$🌟-rank-only$$ pour procéder à la vérification"
    9 "Génial! %%USER%% Vous venez de recevoir votre Server Tag ! Passez maintenant à $$CHANNEL$$. <1/5>"
    10 "%%USER%% Entrez votre tag d'alliance ici <2/5>"
    11 "C'est cool! %%USER%% vous avez maintenant un tag Alliance ! Continuez et passez à $$CHANNEL$$. <2/5>"
    12 "%%USER%% tapez le nom de votre jeu de personnage ici ! <3/5>"
    13 "Parfait! %%USER%% vous avez mis à jour votre nom d'affichage avec le nom de votre jeu de personnage ! Deux étapes supplémentaires, passez à $$CHANNEL$$. <3/5>"
    14 "%%USER%% sélectionnez votre rang d'alliance dans le jeu. <4/5>"
    15 "Bienvenue à"
    16 "Impossible d'ajouter une réaction à l'utilisateur qui a bloqué le bot. Pseudonyme mis à jour"
    17 "Veuillez saisir une balise à 3-4 chiffres"
    18 "Veuillez saisir une balise numérique"
    19 "Veuillez saisir une balise d'alliance de 3 à 4 caractères"
    20 "Merci de ne pas utiliser de caractères spéciaux"
    21 "Veuillez saisir un nom d'utilisateur de 3 à 15 caractères"
)
"russian" (dict
    1 "Шаг 1/5: Введите номер своего сервера ####"
    2 "Нажмите ⁠$$🏰-alliance-only$$, чтобы продолжить проверку"
    3 "Это ОТМЕТЛЕНО внизу канала!"
    4 "Шаг 2/5: Введите тег вашего альянса ####"
    5 "Нажмите $$⁠🎮-game-name-only$$, чтобы продолжить проверку"
    6 "Нет союза? Напишите \"skip\""
    7 "Шаг 3/5: введите название игры, чтобы продолжить"
    8 "Нажмите ⁠$$🌟-rank-only$$, чтобы продолжить проверку"
    9 "Потрясающий! %%USER%% Вы только что получили тег сервера! Теперь перейдите к $$CHANNEL$$. <1/5>"
    10 "%%USER%% Введите здесь тег вашего альянса <2/5>"
    11 "Это здорово! %%USER%% теперь у вас есть тег альянса! Продолжайте и перейдите к $$CHANNEL$$. <2/5>"
    12 "%%USER%% введите здесь свое игровое имя персонажа! <3/5>"
    13 "Идеальный! %%USER%% вы обновили отображаемое имя на игровое имя вашего персонажа! Еще два шага, переходим к $$CHANNEL$$. <3/5>"
    14 "%%USER%% выберите свой внутриигровой рейтинг альянса. <4/5>"
    15 "Добро пожаловать в"
    16 "Невозможно добавить реакцию на пользователя, заблокировавшего бота. Псевдоним обновлен"
    17 "Введите тег из 3-4 цифр"
    18 "Пожалуйста, введите числовой тег"
    19 "Введите тег альянса из 3-4 символов"
    20 "Пожалуйста, не используйте специальные символы"
    21 "Пожалуйста, введите имя пользователя длиной от 3 до 15 символов"
)
"chinese" (dict
    1 "步骤 1/5: 输入您的服务器号码 ####"
    2 "点击 ⁠$$🏰-alliance-only$$ 继续验证"
    3 "这已印在频道底部!"
    4 "步骤 2/5: 输入您的联盟标签 ####"
    5 "点击 $$⁠🎮-game-name-only$$ 继续验证"
    6 " 没有联盟? 输入 \"skip\""
    7 "步骤 3/5: 输入您的游戏名称以继续"
    8 "点击 ⁠$$🌟-rank-only$$ 继续验证"
    9 "惊人的! %%USER%% 您刚刚收到您的服务器标签! 现在前往$$CHANNEL$$. <1/5>"
    10 "%%USER%% 在此输入您的联盟标签 <2/5>"
    11 "这很酷! %%USER%% 您现在拥有联盟标签! 继续并前往$$CHANNEL$$. <2/5>"
    12 "%%USER%% 在这里输入您的角色游戏名称! <3/5>"
    13 "完美的! %%USER%% 您已将您的显示名称更新为您的角色游戏名称! 再执行两步，继续$$CHANNEL$$! <3/5>"
    14 " %%USER%% 选择您的游戏内联盟等级. <4/5>"
    15 "欢迎来到"
    16 "无法向阻止机器人的用户添加反应. 昵称已更新"
    17 "请输入3-4位标签"
    18 "请输入数字标签"
    19 "请输入3-4个字符的联盟标签"
    20 "请不要使用特殊字符"
    21 "请输入3-15个字符的用户名"
)
"arabic" (dict
    1 "الخطوة 1/5: اكتب رقم الخادم الخاص بك ####"
    2 "انقر على ⁠$$🏰-alliance-only$$ لمتابعة عملية التحقق"
    3 "تم ختمه في أسفل القناة!"
    4 "الخطوة 2/5: اكتب علامة التحالف الخاصة بك #### "
    5 "انقر على $$⁠🎮-game-name-only$$ لمتابعة عملية التحقق"
    6 "لا يوجد تحالف؟ اكتب \"skip\""
    7 "الخطوة 3/5: اكتب اسم لعبتك للمتابعة"
    8 "انقر على ⁠$$🌟-rank-only$$ لمتابعة عملية التحقق"
    9 "مذهل! %%USER%% لقد استلمت للتو علامة الخادم الخاصة بك! انتقل الآن إلى $$CHANNEL$$. <1/5>"
    10 "%%USER%% أدخل علامة التحالف الخاصة بك هنا <2/5>"
    11 "ان هذا رائع! %%USER%% لديك الآن علامة تحالف! تابع وانتقل إلى $$CHANNEL$$. <2/5>"
    12 "%%USER%% اكتب اسم لعبة الشخصية الخاصة بك هنا! <3/5>"
    13 "ممتاز! %%USER%% لقد قمت بتحديث اسم العرض الخاص بك إلى اسم لعبة الشخصية الخاصة بك! خطوتان أخريان، تابع إلى $$CHANNEL$$. <3/5>"
    14 "%%USER%% حدد رتبة تحالفك داخل اللعبة. <4/5>"
    15 "مرحبا بك في"
    16 "لا يمكن إضافة رد فعل للمستخدم الذي قام بحظر الروبوت. تم تحديث اللقب"
    17 "الرجاء إدخال علامة مكونة من 3-4 أرقام"
    18 "الرجاء إدخال علامة رقمية"
    19 "الرجاء إدخال علامة تحالف مكونة من 3-4 أحرف"
    20 "الرجاء عدم استخدام أحرف خاصة"
    21 "الرجاء إدخال اسم مستخدم مكون من 3 إلى 15 حرفًا"
)
"korean" (dict
    1 "1/5단계: 서버 번호 ####를 입력하세요 📩"
    2 "확인을 진행하려면 ⁠$$🏰-alliance-only$$를 클릭하세요."
    3 "채널 하단에 스탬프가 찍혀있습니다!"
    4 "2/5단계: 동맹 태그 ####를 입력하세요 🏰"
    5 "확인을 진행하려면 $$⁠🎮-game-name-only$$ 를 클릭하세요."
    6 "얼라이언스가 없나요? \"skip\" 를 입력하세요."
    7 "3/5단계: 계속하려면 게임 이름을 입력하세요 🎮"
    8 "인증을 진행하려면 ⁠$$🌟-rank-only$$를 클릭하세요."
    9 "엄청난! %%USER%% 방금 서버 태그를 받았습니다! 이제 $$CHANNEL$$로 이동하세요. <1/5>"
    10 "%%USER%% 여기에 동맹 태그를 입력하세요 <2/5>"
    11 "이것은 멋지다! %%USER%% 이제 동맹 태그를 가지게 되었습니다! 계속해서 $$CHANNEL$$로 이동하세요. <2/5>"
    12 "%%USER%% 여기에 캐릭터 게임 이름을 입력하세요! <3/5>"
    13 "완벽한! %%USER%% 표시 이름을 캐릭터 게임 이름으로 업데이트했습니다! 두 단계만 더 진행하면 $$CHANNEL$$로 이동합니다. <3/5>"
    14 "%%USER%% 게임 내 동맹 순위를 선택하세요. <4/5>"
    15 "에 오신 것을 환영합니다"
    16 "봇을 차단한 사용자에게는 반응을 추가할 수 없습니다. 닉네임이 업데이트되었습니다."
    17 "3~4자리 태그를 입력해주세요."
    18 "숫자 태그를 입력해주세요."
    19 "연맹 태그를 3~4자로 입력해주세요."
    20 "특수문자는 사용하지 마세요."
    21 "3~15자의 사용자 이름을 입력하세요"

)
"german" (dict
    1 ""
    2 ""
    3 ""
    4 ""
    5 ""
    6 ""
    7 ""
    8 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    15 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"vietnamese" (dict
    1 ""
    2 ""
    3 ""
    4 ""
    5 ""
    6 ""
    7 ""
    8 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    15 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"japanese" (dict
    1 ""
    2 ""
    3 ""
    4 ""
    5 ""
    6 ""
    7 ""
    8 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    15 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"turkish" (dict
    1 ""
    2 ""
    3 ""
    4 ""
    5 ""
    6 ""
    7 ""
    8 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    15 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"portugese" (dict
    1 ""
    2 ""
    3 ""
    4 ""
    5 ""
    6 ""
    7 ""
    8 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    15 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
"korean" (dict
    1 ""
    2 ""
    3 ""
    4 ""
    5 ""
    6 ""
    7 ""
    8 ""
    9 ""
    10 ""
    11 ""
    12 ""
    13 ""
    14 ""
    15 ""
    16 ""
    17 ""
    18 ""
    19 ""
    20 ""
    21 ""
)
}}