{{$languageDB := (dbGet 0 "languageDB").Value}}
{{$languages := sdict
"arabic" (dict
	1 "لا يوجد تحالف؟ اكتب \"skip\""
	2 "مذهل! <@!> لقد استلمت للتو علامة الخادم الخاصة بك! انتقل الآن إلى <#> <1/5>"
	3 "<@!> أدخل علامة التحالف الخاصة بك هنا <2/5>"
	4 "ان هذا رائع! <@!> لديك الآن علامة تحالف! تابع وانتقل إلى <#> <2/5>"
	5 "<@!> اكتب اسم لعبة الشخصية الخاصة بك هنا! <3/5>"
	6 "ممتاز! <@!> لقد قمت بتحديث اسم العرض الخاص بك إلى اسم لعبة الشخصية الخاصة بك! خطوتان أخريان، تابع إلى <#> <3/5>"
	7 "<@!> حدد رتبة تحالفك داخل اللعبة. <4/5>"
	8 "لا يمكن إضافة رد فعل للمستخدم الذي قام بحظر الروبوت. تم تحديث اللقب"
	9 "الرجاء إدخال علامة مكونة من 3-4 أرقام"
	10 "الرجاء إدخال علامة رقمية"
	11 "الرجاء إدخال علامة تحالف مكونة من 3-4 أحرف"
	12 "الرجاء عدم استخدام أحرف خاصة"
	13 "الرجاء إدخال اسم مستخدم مكون من 3 إلى 15 حرفًا"
	14 "لنبدأ <@!>، انتقل إلى <#> <0/5>"
	15 "حسنًا <@!>، دعنا نجهزك للانضمام والتحقق!"
	16 "تفضل <@!>، لقد بدأنا للتو! <0/5>"
	17 "أخيراً!! <@!> أنت هنا!! الخطوة الأخيرة إلى الجانب الآخر!! <5/5>"
	18 "ها ها ها ها! لقد فعلتها! <@!> مرحبًا بك في الجانب الآخر!"
	19 "أحسنت! <@!> استعد الآن للخطوة الأخيرة⁠ <#> <5/5>"
	20 "مرحبا هناك أيها المحارب! 🤺\n\n**شكرًا لك على الانضمام، يرجى المتابعة للانضمام والتحقق <@!>.** ✅\n\n- سيتم إرشادك الآن برموز <@!765316548516380732> للانضمام والتحقق من خلال الخطوات التالية:\n 1 - 🚩 علامة الخادم: اكتب رقم الخادم الخاص بك.\n 2 - 🏰 علامة التحالف: اكتب علامة التحالف الخاصة بك.\n 3 - 🎮 اسم اللعبة : اكتب اسم اللعبة الخاص بك.\n 4 - 🌟 تصنيف التحالف: اختر تصنيف التحالف الخاص بك.\n 5 - 📃 قواعد الديسكورد: اقرأ وتحقق.\n\n> - سيستغرق ذلك أقل من دقيقة، برجاء اتباع تعليمات البوت.\n\n⚠️ يمكنك فقط تحديد **لغة واحدة**، إذا قمت بتحديد لغتين، فسوف يستجيب لك الروبوت باللغة الأخيرة المحددة، للتعديل والإصلاح، ارجع إلى <#L> ⚠️\n\n> 💥 **تلميح: تم تخصيص هذه الرسالة بناءً على اللغة التي حددتها آخر مرة** 💥\n\n### **نحن في انتظاركم على الجانب الآخر!** 🌀\n\n### **تفاعل باستخدام ✅ للمتابعة والبدء.**\n## 👉 <#S>"
)
"korean" (dict
	1 "얼라이언스가 없나요? \"skip\" 를 입력하세요."
	2 "엄청난! <@!> 방금 서버 태그를 받았습니다! 이제 <#>로 이동하세요 <1/5>"
	3 "<@!> 여기에 동맹 태그를 입력하세요 <2/5>"
	4 "이것은 멋지다! <@!> 이제 동맹 태그를 가지게 되었습니다! 계속해서 <#> 로 이동하세요 <2/5>"
	5 "<@!> 여기에 캐릭터 게임 이름을 입력하세요! <3/5>"
	6 "완벽한! <@!> 표시 이름을 캐릭터 게임 이름으로 업데이트했습니다! 두 단계만 더 진행하면 <#> 로 이동합니다 <3/5>"
	7 "<@!> 게임 내 동맹 순위를 선택하세요 <4/5>"
	8 "봇을 차단한 사용자에게는 반응을 추가할 수 없습니다. 닉네임이 업데이트되었습니다"
	9 "3~4자리 태그를 입력해주세요"
	10 "숫자 태그를 입력해주세요"
	11 "연맹 태그를 3~4자로 입력해주세요"
	12 "특수문자는 사용하지 마세요"
	13 "3~15자의 사용자 이름을 입력하세요"
	14 "<@!>를 시작하고 <#>로 진행하세요. <0/5>"
	15 "좋습니다 <@!> 님, 등록 및 인증을 받을 수 있도록 준비하겠습니다!"
	16 "<@!> 님, 이제 막 시작했습니다! <0/5>"
	17 "마지막으로!! <@!> 여기 계시네요!! 반대편으로 가는 마지막 단계!! <5/5>"
	18 "하하하! 네가 해냈어! <@!> 반대편에 오신 것을 환영합니다!"
	19 "잘하셨어요! <@!>님은 이제 마지막 단계를 준비하세요⁠ <#> <5/5>"
	20 "안녕하세요 용사님! 🤺\n\n**<@!> 가입해 주셔서 감사합니다. 온보딩 및 인증을 진행하세요.** ✅\n\n- 이제 <@!765316548516380732> 코딩에 대한 안내를 받아 다음 단계를 통해 온보딩 및 인증을\n받을 수 있습니다.\n 1 - 🚩 서버 태그 : 서버 번호를 입력하세요.\n 2 - 🏰 동맹 태그 : 동맹 태그를 입력하세요.\n 3 - 🎮 게임 이름 : 게임 이름을 입력하세요.\n 4 - 🌟 연맹 순위 : 연맹 순위를 선택하세요.\n 5 - 📃 불일치 규칙: 읽고 확인하세요.\n > - 이 과정은 1분도 채 걸리지 않습니다. 봇의 지시를 따라주세요.\n\n⚠️**한 가지 언어**만 선택할 수 있습니다. 두 가지 언어를 선택한 경우 봇은 마지막으로 선택한 언어로 응답합니다. 조정하고 수정하려면 <#L>로 돌아가세요 ⚠️\n\n> 품 **힌트: 이 메시지는 마지막으로 선택한 언어에 따라 맞춤설정되었습니다** 품\n\n### **저편에서 여러분을 기다리고 있습니다!** 🌀\n\n### **계속 진행하려면 ✅로 반응하고 시작하세요.**\n## 👉 <#S>"
)
"german" (dict
	1 "Kein Bündnis? Geben Sie \"skip\" ein"
	2 "Eindrucksvoll! <@!> Sie haben gerade Ihr Server-Tag erhalten! Fahren Sie nun mit <#> fort <1/5>"
	3 "<@!> Geben Sie hier Ihr Allianz-Tag ein <2/5>"
	4 "Das ist cool! <@!> Sie haben jetzt ein Allianz-Tag! Fahren Sie fort und fahren Sie mit <#> fort <2/5>"
	5 "<@!> Geben Sie hier Ihren Charakter-Spielnamen ein! <3/5>"
	6 "Perfekt! <@!> Sie haben Ihren Anzeigenamen auf den Namen Ihres Charakterspiels aktualisiert! Zwei weitere Schritte, fahren Sie mit <#> fort <3/5>"
	7 "<@!> wähle deinen Allianzrang im Spiel aus <4/5"
	8 "Dem Benutzer, der den Bot blockiert hat, kann keine Reaktion hinzugefügt werden. Spitzname aktualisiert"
	9 "Bitte geben Sie ein 3-4-stelliges Tag ein"
	10 "Bitte geben Sie ein numerisches Tag ein"
	11 "Bitte geben Sie einen Allianz-Tag mit 3-4 Zeichen ein"
	12 "Bitte verwenden Sie keine Sonderzeichen"
	13 "Bitte geben Sie einen 3-15 Zeichen langen Benutzernamen ein"
	14 "Beginnen wir mit <@!> und fahren mit <#> <0/5> fort"
	15 "Alles klar, <@!>, bereiten wir dich auf das Onboarding und die Verifizierung vor!"
	16 "Los geht's <@!>, wir haben gerade erst angefangen! <0/5>"
	17 "Endlich!! <@!> Du bist hier!! Letzter Schritt auf die andere Seite!! <5/5>"
	18 "Hahaha! Du hast es geschafft! <@!> Willkommen auf der anderen Seite!"
	19 "Gut gemacht! <@!> Machen Sie sich jetzt bereit für den letzten Schritt⁠ <#> <5/5>"
	20 "Hallo Krieger! 🤺\n\n**<@!> Vielen Dank für Ihre Teilnahme. Bitte melden Sie sich an und verifizieren Sie sich.** ✅\n\n- Sie werden nun mit den Codierungen von <@!765316548516380732> zum Onboarding und zur Verifizierung durch die folgenden Schritte geführt:\n 1 - 🚩 Server-Tag: Geben Sie Ihre Servernummer ein.\n 2 - 🏰 Allianz-Tag: Geben Sie Ihr Allianz-Tag ein.\n 3 - 🎮 Spielname: Geben Sie Ihren Spielnamen ein.\n 4 - 🌟 Allianzrang: Wählen Sie Ihren Allianzrang.\n 5 – 📃 Discord-Regeln: Lesen und überprüfen.\n\n> - Dies dauert weniger als eine Minute. Bitte folgen Sie den Anweisungen des Bots.\n\n⚠️Sie können nur **EINE Sprache** auswählen. Wenn Sie zwei Sprachen ausgewählt haben, antwortet Ihnen der Bot mit der zuletzt ausgewählten Sprache. Zum Anpassen und Korrigieren gehen Sie zurück zu <#L> ⚠️\n\n> 💥 **TIPP: Diese Nachricht wird basierend auf der zuletzt ausgewählten Sprache angepasst** 💥\n\n### **Wir warten auf der anderen Seite auf dich!** 🌀\n\n### **Reagieren Sie mit einem ✅, um fortzufahren und loszulegen.**\n## 👉 <#S>"
)
"vietnamese" (dict
	1 "Không có liên minh? Gõ \"skip\""
	2 "Tuyệt vời! <@!> Bạn vừa nhận được Thẻ máy chủ của mình! Bây giờ hãy chuyển sang <#> <1/5>"
	3 "<@!> Nhập thẻ liên minh của bạn vào đây <2/5>"
	4 "Cái này hay đấy! <@!> bạn hiện có Thẻ Liên minh! Tiếp tục và tiến tới <#> <2/5>"
	5 "<@!> nhập Tên trò chơi nhân vật của bạn vào đây! <3/5>"
	6 "Hoàn hảo! <@!> bạn đã cập nhật tên hiển thị thành Tên trò chơi nhân vật của mình! Hai bước nữa, tiến tới <#> <3/5>"
	7 "<@!> chọn thứ hạng liên minh trong trò chơi của bạn <4/5>"
	8 "Không thể thêm phản ứng cho người dùng đã chặn bot. Đã cập nhật biệt hiệu"
	9 "Vui lòng nhập thẻ 3-4 chữ số"
	10 "Vui lòng nhập thẻ số"
	11 "Vui lòng nhập thẻ liên minh 3-4 ký tự"
	12 "Vui lòng không sử dụng ký tự đặc biệt"
	13 "Vui lòng nhập tên người dùng 3-15 ký tự"
	14 "Hãy bắt đầu <@!>, tiến tới <#> <0/5>"
	15 "Được rồi <@!>, hãy chuẩn bị sẵn sàng để bạn tham gia và xác minh!"
	16 "Của bạn đây <@!>, chúng ta vừa mới bắt đầu! <0/5>"
	17 "Cuối cùng!! <@!> Bạn đang ở đây!! Bước cuối cùng sang phía bên kia!! <5/5>"
	18 "Hahaha! Bạn đã thực hiện nó! <@!> Chào mừng bạn đến với phía bên kia!"
	19 "Làm tốt! <@!> bây giờ hãy sẵn sàng cho bước cuối cùng⁠ <#> <5/5>"
	20 "Xin chào chiến binh! 🤺\n\n**<@!> Cảm ơn bạn đã tham gia, vui lòng tiếp tục tham gia và xác minh.** ✅\n\n- Bây giờ, bạn sẽ được hướng dẫn cách mã hóa <@!765316548516380732> để tham gia và xác minh thông qua các bước sau:\n 1 - 🚩 Thẻ máy chủ : Nhập số máy chủ của bạn.\n 2 - 🏰 Thẻ liên minh : Nhập Thẻ liên minh của bạn.\n 3 - 🎮 Tên trò chơi: Nhập tên trò chơi của bạn.\n 4 - 🌟 Xếp hạng Liên minh : Chọn Xếp hạng Liên minh của bạn.\n 5 - 📃 Quy tắc bất hòa: Đọc và xác minh.\n\n> - Quá trình này sẽ mất chưa đầy một phút, vui lòng làm theo hướng dẫn của bot.\n\n⚠️Bạn chỉ có thể chọn **MỘT Ngôn ngữ**, nếu bạn chọn 2 ngôn ngữ, bot sẽ phản hồi bạn bằng ngôn ngữ được chọn gần đây nhất, để điều chỉnh và sửa lỗi, hãy quay lại <#L> ⚠️\n\n> 🔥 **GỢI Ý: Thông báo này được tùy chỉnh dựa trên ngôn ngữ bạn đã chọn gần đây nhất** ✔️\n\n### **Chúng tôi đang đợi bạn ở phía bên kia!** 🌀\n\n### **Phản ứng bằng ✅ để tiếp tục và bắt đầu.**\n## 👉 <#S>"
)
"japanese" (dict
	1 "同盟はありませんか？ \"skip\" ップ」と入力してください"
	2 " 素晴らしい！ <@!> サーバー タグを受け取りました。 <#> に進みます <1/5>"
	3 "<@!> ここに同盟タグを入力してください <2/5>"
	4 "これはカッコいい！ <@!> さんは同盟タグを獲得しました! 続行して <#> に進みます <2/5>"
	5 "<@!> ここにキャラクター ゲーム名を入力してください! <3/5>"
	6 "完璧！ <@!> 表示名をキャラクター ゲーム名に更新しました! さらに 2 つの手順を実行して、<#> に進みます <3/5>"
	7 "<@!> はゲーム内の同盟ランクを選択します <4/5>"
	8 "ボットをブロックしたユーザーにリアクションを追加することはできません。 ニックネームを更新しました"
	9 "3-4桁のタグを入力してください"
	10 "数字タグを入力してください"
	11 "3-4文字の同盟タグを入力してください"
	12 "特殊文字は使用しないでください"
	13 "3-15 文字のユーザー名を入力してください"
	14 "始めましょう <@!>、<#> <0/5> に進みます"
	15 "わかりました <@!>、オンボーディングと認証の準備をしましょう!"
	16 "どうぞ <@!>、まだ始まったばかりです! <0/5>"
	17 "ついに！！ <@!> ここにいます!! 向こう側への最終段階!! <5/5>"
	18 "ははは！ やった！ <@!> 向こう側へようこそ!"
	19 "よくやった！ <@!> は最終ステップの準備をしてください⁠ <#> <5/5>"
	20 "こんにちは、戦士です！ 🤺\n\n**<@!> ご参加いただきありがとうございます。引き続き登録と認証を行ってください。** ✅\n\n- <@!765316548516380732> のコーディングのガイドが表示されるので、次の手順に従ってオンボーディングおよび検証を行います。\n 1 - 🚩 サーバータグ : サーバー番号を入力します。\n 2 - 🏰 アライアンスタグ : アライアンスタグを入力します。\n 3 - 🎮 ゲーム名 : ゲーム名を入力します。\n 4 - 🌟 同盟ランク: 同盟ランクを選択します。\n 5 - 📃 Discord ルール : 読んで確認してください。\n\n> - これには 1 分もかかりません。ボットの指示に従ってください。\n\n⚠️**1 つの言語** のみを選択できます。2 つの言語を選択した場合、ボットは最後に選択した言語で応答します。調整して修正するには、<#L> に戻ってください ⚠️\n\n> 💥 **ヒント: このメッセージは、最後に選択した言語に基づいてカスタマイズされます** 💥\n\n### **向こう側でお待ちしています!** 🌀\n\n### **続行して開始するには、「✅」をクリックしてください。**\n## 👉 <#S>"
)
}}
{{range $k, $v := $languages}}
	{{$languageDB.Set $k $v}}
{{end}}
{{dbSet 0 "languageDB" $languageDB}}