{{/*
		Made by ranger_4297 (765316548516380732)

	Trigger Type: `Command`
	Trigger: `ldb`

	©️ RhykerWells 2020-Present
	GNU, GPLV3 License

	Made with love, support me using https://ko-fi.com/rhykerwells
*/}}

{{$languages := sdict
"english" (dict
	1 "No alliance? Type \"skip\""
	2 "Awesome! <@!> You've just received your Server Tag! Now proceed to <#> <1/5>"
	3 "<@!> Enter your alliance tag here <2/5>"
	4 "This is cool! <@!> you now have an Alliance Tag! Continue and proceed to <#> <2/5>"
	5 "<@!> type your Character Game Name over here! <3/5>"
	6 "Perfect! <@!> you've updated your display name to your Character Game Name! Two more steps, proceed to <#> <3/5>"
	7 "<@!> select your in-game alliance rank <4/5>"
	8 "Cannot add reaction to user who has blocked bot. Nickname updated"
	9 "Please input a 3-4 digit tag"
	10 "Please input a numeric tag"
	11 "Please input a 3-4 character alliance tag"
	12 "Please don't use special characters"
	13 "Please input a 3-15 character username"
	14 "Let's get started <@!>, proceed to <#> <0/5>"
	15 "Alright <@!>, let's get you ready to be onboarded and verified!"
	16 "Here you go <@!>, we just got started! <0/5>"
	17 "Finally!! <@!> You are here!! Final step to the other side!! <5/5>"
	18 "Hahaha! You made it! <@!> Welcome to the other side!"
	19 "Well done! <@!> now get ready for the final step⁠ <#> <5/5>"
	20 "### Welcome <@!> to KG World - WOR  🌀\n> Please follow the 5 Verification Steps, coded by <@!765316548516380732>\n> - This will take less than a minute.\n> - To change language 👉 <#L>\n\n~ *The other side awaits you* 💫\n### **👇 Click  ✅  to get started.**"
	21 "**<@!> This is WOR, a private KG World Server.**\n - We respect competition.\n - We welcome everyone.\n - Stay respectful.\n - Most importantly, let's have fun.\n### **We are waiting for you on the other side** 🌀\n\n### **React with a ✅  to proceed.**"
	22 "<@!> Select your current Alliance Rank.\n\n### 👉 <#>"
	23 "<@!> You have been placed on a cooldown for this reaction.\nCooldown ends in **<T>**"
)
"spanish" (dict
	1 "¿Sin alianza? Escribe \"skip\""
	2 "¡Impresionante! <@!> ¡Acabas de recibir tu etiqueta de servidor! Ahora procede a <#> <1/5>"
	3 "<@!> Introduce tu etiqueta de alianza aquí <2/5>"
	4 "¡Esto es genial! <@!> ¡ahora tienes una etiqueta de alianza! Continúe y pase a <#> <2/5>"
	5 "<@!> ¡escribe el nombre del juego de tu personaje aquí! <3/5>"
	6 "¡Perfecto! <@!> ¡Has actualizado tu nombre para mostrar al nombre del juego de tu personaje! Dos pasos más, continúa con <#> <3/5>"
	7 "<@!> selecciona tu rango de alianza en el juego <4/5>"
	8 "No se puede agregar una reacción al usuario que ha bloqueado el bot. Apodo actualizado"
	9 "Ingrese una etiqueta de 3 a 4 dígitos"
	10 "Ingrese una etiqueta numérica"
	11 "Ingrese una etiqueta de alianza de 3-4 caracteres"
	12 "Por favor no utilices caracteres especiales"
	13 "Ingrese un nombre de usuario de 3 a 15 caracteres"
	14 "Comencemos <@!>, continúe con <#> <0/5>"
	15 "Muy bien <@!>, ¡vamos a prepararte para ser incorporado y verificado!"
	16 "Aquí tienes <@!>, ¡acabamos de empezar! <0/5>"
	17 "¡¡Finalmente!! <@!> ¡¡Estás aquí!! ¡¡Último paso al otro lado!! <5/5>"
	18 "¡Jajaja! ¡Lo hiciste! <@!> ¡Bienvenido al otro lado!"
	19 "¡Bien hecho! <@!> ahora prepárate para el paso final⁠ <#> <5/5>"
	20 "### Bienvenido <@!> a KG World - WOR 🌀\n> Siga los 5 pasos de verificación, codificados por <@!765316548516380732>\n> - Esto tomará menos de un minuto.\n> - Para cambiar idioma 👉 <#L>\n\n~ *El otro lado te espera* 💫\n### **👇 Haz clic en ✅ para comenzar.**"
	21 "**<@!> Este es WOR, un servidor privado de KG World.**\n - Respetamos la competencia.\n - Damos la bienvenida a todos.\n - Sea respetuoso.\n - Lo más importante es que nos divirtamos.\n### **Te esperamos del otro lado** 🌀\n\n### **Reacciona con un ✅ para continuar.**"
	22 "<@!> Seleccione su rango de alianza actual.\n\n### 👉 <#>"
	23 "<@!> Te han puesto en tiempo de reutilización para esta reacción.\nEl tiempo de reutilización termina en **<T>**"
)
"french" (dict
	1 "Pas d'alliance ? Tapez \"skip\""
	2 "Génial! <@!> Vous venez de recevoir votre Server Tag ! Passez maintenant à <#> <1/5>"
	3 "<@!> Entrez votre tag d'alliance ici <2/5>"
	4 "C'est cool! <@!> vous avez maintenant un tag Alliance ! Continuez et passez à <#> <2/5>"
	5 "<@!> tapez le nom de votre jeu de personnage ici ! <3/5>"
	6 "Parfait! <@!> vous avez mis à jour votre nom d'affichage avec le nom de votre jeu de personnage ! Deux étapes supplémentaires, passez à <#> <3/5>"
	7 "<@!> sélectiQonnez votre rang d'alliance dans le jeu <4/5>"
	8 "Impossible d'ajouter une réaction à l'utilisateur qui a bloqué le bot. Pseudonyme mis à jour"
	9 "Veuillez saisir une balise à 3-4 chiffres"
	10 "Veuillez saisir une balise numérique"
	11 "Veuillez saisir une balise d'alliance de 3 à 4 caractères"
	12 "Merci de ne pas utiliser de caractères spéciaux"
	13 "Veuillez saisir un nom d'utilisateur de 3 à 15 caractères"
	14 "Commençons <@!>, passez à <#> <0/5>"
	15 "Très bien <@!>, préparons-nous à être intégré et vérifié !"
	16 "Et voilà <@!>, nous venons tout juste de commencer ! <0/5>"
	17 "Enfin!! <@!> Vous êtes ici !! Dernière étape vers l'autre côté !! <5/5>"
	18 "Hahaha! Tu l'as fait! <@!> Bienvenue de l'autre côté !"
	19 "Bien joué! <@!> préparez-vous maintenant pour la dernière étape⁠ <#> <5/5>"
	20 "### Bienvenue <@!> dans KG World - WOR 🌀\n> Veuillez suivre les 5 étapes de vérification, codées par <@!765316548516380732>\n> - Cela prendra moins d'une minute.\n> - Pour modifier langue 👉 <#L>\n\n~ *L'autre côté vous attend* 💫\n### **👇 Cliquez sur ✅ pour commencer.**"
	21 "**<@!> Voici WOR, un serveur mondial privé de KG.**\n - Nous respectons la concurrence.\n - Nous souhaitons la bienvenue à tout le monde.\n - Restez respectueux.\n - Et surtout, amusons-nous.\n### **On vous attend de l'autre côté** 🌀\n\n### **Réagissez avec un ✅ pour continuer.**"
	22 "<@!> Sélectionnez votre rang d'alliance actuel.\n\n### 👉 <#>"
	23 "<@!> Vous avez été placé en temps de recharge pour cette réaction.\nLe temps de recharge se termine dans **<T>**"
)
"russian" (dict
	1 "Нет союза? Напишите \"skip\""
	2 "Потрясающий! <@!> Вы только что получили тег сервера! Теперь перейдите к <#> <1/5>"
	3 "<@!> Введите здесь тег вашего альянса <2/5>"
	4 "Это здорово! <@!> теперь у вас есть тег альянса! Продолжайте и перейдите к <#> <2/5>"
	5 "<@!> введите здесь свое игровое имя персонажа! <3/5>"
	6 "Идеальный! <@!> вы обновили отображаемое имя на игровое имя вашего персонажа! Еще два шага, переходим к <#> <3/5>"
	7 "<@!> выберите свой внутриигровой рейтинг альянса <4/5>"
	8 "Невозможно добавить реакцию на пользователя, заблокировавшего бота. Псевдоним обновлен"
	9 "Введите тег из 3-4 цифр"
	10 "Пожалуйста, введите числовой тег"
	11 "Введите тег альянса из 3-4 символов"
	12 "Пожалуйста, не используйте специальные символы"
	13 "Пожалуйста, введите имя пользователя длиной от 3 до 15 символов"
	14 "Давайте начнем <@!>, перейдите к <#> <0/5>"
	15 "Хорошо, <@!>, подготовим тебя к регистрации и проверке!"
	16 "Держи <@!>, мы только начали! <0/5>"
	17 "Окончательно!! <@!> Ты здесь!! Последний шаг на другую сторону!! <5/5>"
	18 "Ха-ха-ха! Ты сделал это! <@!> Добро пожаловать на другую сторону"
	19 "Отличная работа! <@!> теперь приготовьтесь к последнему шагу⁠ <#> <5/5>"
	20 "### Добро пожаловать <@!> в KG World - WOR 🌀\n> Пожалуйста, выполните 5 шагов проверки под кодом <@!765316548516380732>\n> - Это займет меньше минуты.\n> - Чтобы изменить язык 👉 <#L>\n\n~ *Вас ждет другая сторона* 💫\n### **👇 Нажмите ✅, чтобы начать.**"
	21 "**<@!> Это WOR, частный мировой сервер KG.**\n - Мы уважаем конкуренцию.\n - Мы приветствуем всех.\n - Сохраняйте уважение.\n - Самое главное, давайте веселиться.\n### **Мы ждём вас на другой стороне** 🌀\n\n### **Чтобы продолжить, нажмите ✅.**"
	22 "<@!> Выберите свой текущий ранг Альянса.\n\n### 👉 <#>"
	23 "<@!> Для этой реакции у вас установлен период восстановления.\nВремя восстановления заканчивается через **<T>**"
)
"chinese" (dict
	1 "没有联盟? 输入 \"skip\""
	2 "惊人的! <@!> 您刚刚收到您的服务器标签! 现在前往 <#> <1/5>"
	3 "<@!> 在此输入您的联盟标签 <2/5>"
	4 "这很酷! <@!> 您现在拥有联盟标签! 继续并前往<#> <2/5>"
	5 "<@!> 在这里输入您的角色游戏名称! <3/5>"
	6 "完美的! <@!> 您已将您的显示名称更新为您的角色游戏名称! 再执行两步，继续 <#>! <3/5>"
	7 "<@!> 选择您的游戏内联盟等级 <4/5>"
	8 "无法向阻止机器人的用户添加反应. 昵称已更新"
	9 "请输入3-4位标签"
	10 "请输入数字标签"
	11 "请输入3-4个字符的联盟标签"
	12 "请不要使用特殊字符"
	13 "请输入3-15个字符的用户名"
	14 "让我们开始吧 <@!>，继续 <#> <0/5>"
	15 "好的 <@!>，让我们为您准备好加入和验证！"
	16 "给你 <@!>，我们才刚刚开始！ <0/5>"
	17 "最后！! <@!> 你在这里！！最后一步到另一边！ <5/5>"
	18 "哈哈哈! 你做到了！ <@!> 欢迎来到另一边！"
	19 "做得好! <@!> 现在准备好最后一步⁠ <#> <5/5>"
	20 "### 欢迎 <@!> 来到 KG World - WOR 🌀\n> 请按照 5 个验证步骤进行操作，编码为 <@!765316548516380732>\n> - 这将需要不到一分钟的时间。\n> - 要更改 语言 👉 <#L>\n\n~ *另一边在等你* 💫\n### **👇 点击 ✅ 开始。**"
	21 "**<@!> 这是 WOR，一个私人 KG World 服务器。**\n - 我们尊重竞争。\n - 我们欢迎所有人。\n - 保持尊重。\n - 最重要的是，让我们玩得开心。\n### **我们在另一边等你** 🌀\n\n### **按下 ✅ 即可继续。**"
	22 "<@!> 选择您当前的联盟排名。\n\n### 👉 <#>"
	23 "<@!> 您已被置于此反应的冷却时间。\n冷却时间以 **<T>** 结束"
)
}}
{{dbSet 0 "languageDB" $languages}}