{{$languages := sdict
"english" (dict
	1 "No alliance? Type \"skip\""
	2 "Awesome! <@!> You've just received your Server Tag! Now proceed to <#> <1/5>"
	3 "<@!> Enter your alliance tag here <2/5>"
	4 "This is cool! <@!> you now have an Alliance Tag! Continue and proceed to <#> <2/5>"
	5 "<@!> type your Character Game Name over here! <3/5>"
	6 "Perfect! <@!> you've updated your display name to your Character Game Name! Two more steps, proceed to <#> <3/5>"
	7 "<@!> select your in-game alliance rank <4/5>"
	8 "Cannot add reaction to user who has blocked bot. Nickname updated"
	9 "Please input a 3-4 digit tag"
	10 "Please input a numeric tag"
	11 "Please input a 3-4 character alliance tag"
	12 "Please don't use special characters"
	13 "Please input a 3-15 character username"
)
"spanish" (dict
	1 "¿Sin alianza? Escribe \"skip\""
	2 "¡Impresionante! <@!> ¡Acabas de recibir tu etiqueta de servidor! Ahora procede a <#> <1/5>"
	3 "<@!> Introduce tu etiqueta de alianza aquí <2/5>"
	4 "¡Esto es genial! <@!> ¡ahora tienes una etiqueta de alianza! Continúe y pase a <#> <2/5>"
	5 "<@!> ¡escribe el nombre del juego de tu personaje aquí! <3/5>"
	6 "¡Perfecto! <@!> ¡Has actualizado tu nombre para mostrar al nombre del juego de tu personaje! Dos pasos más, continúa con <#> <3/5>"
	7 "<@!> selecciona tu rango de alianza en el juego <4/5>"
	8 "No se puede agregar una reacción al usuario que ha bloqueado el bot. Apodo actualizado"
	9 "Ingrese una etiqueta de 3 a 4 dígitos"
	10 "Ingrese una etiqueta numérica"
	11 "Ingrese una etiqueta de alianza de 3-4 caracteres"
	12 "Por favor no utilices caracteres especiales"
	13 "Ingrese un nombre de usuario de 3 a 15 caracteres"
)
"french" (dict
	1 "Pas d'alliance ? Tapez \"skip\""
	2 "Génial! <@!> Vous venez de recevoir votre Server Tag ! Passez maintenant à <#> <1/5>"
	3 "<@!> Entrez votre tag d'alliance ici <2/5>"
	4 "C'est cool! <@!> vous avez maintenant un tag Alliance ! Continuez et passez à <#> <2/5>"
	5 "<@!> tapez le nom de votre jeu de personnage ici ! <3/5>"
	6 "Parfait! <@!> vous avez mis à jour votre nom d'affichage avec le nom de votre jeu de personnage ! Deux étapes supplémentaires, passez à <#> <3/5>"
	7 "<@!> sélectionnez votre rang d'alliance dans le jeu <4/5>"
	8 "Impossible d'ajouter une réaction à l'utilisateur qui a bloqué le bot. Pseudonyme mis à jour"
	9 "Veuillez saisir une balise à 3-4 chiffres"
	10 "Veuillez saisir une balise numérique"
	11 "Veuillez saisir une balise d'alliance de 3 à 4 caractères"
	12 "Merci de ne pas utiliser de caractères spéciaux"
	13 "Veuillez saisir un nom d'utilisateur de 3 à 15 caractères"
)
"russian" (dict
	1 "Нет союза? Напишите \"skip\""
	2 "Потрясающий! <@!> Вы только что получили тег сервера! Теперь перейдите к <#> <1/5>"
	3 "<@!> Введите здесь тег вашего альянса <2/5>"
	4 "Это здорово! <@!> теперь у вас есть тег альянса! Продолжайте и перейдите к <#> <2/5>"
	5 "<@!> введите здесь свое игровое имя персонажа! <3/5>"
	6 "Идеальный! <@!> вы обновили отображаемое имя на игровое имя вашего персонажа! Еще два шага, переходим к <#> <3/5>"
	7 "<@!> выберите свой внутриигровой рейтинг альянса <4/5>"
	8 "Невозможно добавить реакцию на пользователя, заблокировавшего бота. Псевдоним обновлен"
	9 "Введите тег из 3-4 цифр"
	10 "Пожалуйста, введите числовой тег"
	11 "Введите тег альянса из 3-4 символов"
	12 "Пожалуйста, не используйте специальные символы"
	13 "Пожалуйста, введите имя пользователя длиной от 3 до 15 символов"
)
"chinese" (dict
	1 " 没有联盟? 输入 \"skip\""
	2 "惊人的! <@!> 您刚刚收到您的服务器标签! 现在前往 <#> <1/5>"
	3 "<@!> 在此输入您的联盟标签 <2/5>"
	4 "这很酷! <@!> 您现在拥有联盟标签! 继续并前往<#> <2/5>"
	5 "<@!> 在这里输入您的角色游戏名称! <3/5>"
	6 "完美的! <@!> 您已将您的显示名称更新为您的角色游戏名称! 再执行两步，继续 <#>! <3/5>"
	7 " <@!> 选择您的游戏内联盟等级 <4/5>"
	8 "无法向阻止机器人的用户添加反应. 昵称已更新"
	9 "请输入3-4位标签"
	10 "请输入数字标签"
	11 "请输入3-4个字符的联盟标签"
	12 "请不要使用特殊字符"
	13 "请输入3-15个字符的用户名"
)
"arabic" (dict
	1 "لا يوجد تحالف؟ اكتب \"skip\""
	2 "مذهل! <@!> لقد استلمت للتو علامة الخادم الخاصة بك! انتقل الآن إلى <#> <1/5>"
	3 "<@!> أدخل علامة التحالف الخاصة بك هنا <2/5>"
	4 "ان هذا رائع! <@!> لديك الآن علامة تحالف! تابع وانتقل إلى <#> <2/5>"
	5 "<@!> اكتب اسم لعبة الشخصية الخاصة بك هنا! <3/5>"
	6 "ممتاز! <@!> لقد قمت بتحديث اسم العرض الخاص بك إلى اسم لعبة الشخصية الخاصة بك! خطوتان أخريان، تابع إلى <#> <3/5>"
	7 "<@!> حدد رتبة تحالفك داخل اللعبة. <4/5>"
	8 "لا يمكن إضافة رد فعل للمستخدم الذي قام بحظر الروبوت. تم تحديث اللقب"
	9 "الرجاء إدخال علامة مكونة من 3-4 أرقام"
	10 "الرجاء إدخال علامة رقمية"
	11 "الرجاء إدخال علامة تحالف مكونة من 3-4 أحرف"
	12 "الرجاء عدم استخدام أحرف خاصة"
	13 "الرجاء إدخال اسم مستخدم مكون من 3 إلى 15 حرفًا"
)
"korean" (dict
	1 "얼라이언스가 없나요? \"skip\" 를 입력하세요."
	2 "엄청난! <@!> 방금 서버 태그를 받았습니다! 이제 <#>로 이동하세요 <1/5>"
	3 "<@!> 여기에 동맹 태그를 입력하세요 <2/5>"
	4 "이것은 멋지다! <@!> 이제 동맹 태그를 가지게 되었습니다! 계속해서 <#> 로 이동하세요 <2/5>"
	5 "<@!> 여기에 캐릭터 게임 이름을 입력하세요! <3/5>"
	6 "완벽한! <@!> 표시 이름을 캐릭터 게임 이름으로 업데이트했습니다! 두 단계만 더 진행하면 <#> 로 이동합니다 <3/5>"
	7 "<@!> 게임 내 동맹 순위를 선택하세요 <4/5>"
	8 "봇을 차단한 사용자에게는 반응을 추가할 수 없습니다. 닉네임이 업데이트되었습니다"
	9 "3~4자리 태그를 입력해주세요"
	10 "숫자 태그를 입력해주세요"
	11 "연맹 태그를 3~4자로 입력해주세요"
	12 "특수문자는 사용하지 마세요"
	13 "3~15자의 사용자 이름을 입력하세요"
)
"german" (dict
	1 "Kein Bündnis? Geben Sie \"skip\" ein"
	2 "Eindrucksvoll! <@!> Sie haben gerade Ihr Server-Tag erhalten! Fahren Sie nun mit <#> fort <1/5>"
	3 "<@!> Geben Sie hier Ihr Allianz-Tag ein <2/5>"
	4 "Das ist cool! <@!> Sie haben jetzt ein Allianz-Tag! Fahren Sie fort und fahren Sie mit <#> fort <2/5>"
	5 "<@!> Geben Sie hier Ihren Charakter-Spielnamen ein! <3/5>"
	6 "Perfekt! <@!> Sie haben Ihren Anzeigenamen auf den Namen Ihres Charakterspiels aktualisiert! Zwei weitere Schritte, fahren Sie mit <#> fort <3/5>"
	7 "<@!> wähle deinen Allianzrang im Spiel aus <4/5"
	8 "Dem Benutzer, der den Bot blockiert hat, kann keine Reaktion hinzugefügt werden. Spitzname aktualisiert"
	9 "Bitte geben Sie ein 3-4-stelliges Tag ein"
	10 "Bitte geben Sie ein numerisches Tag ein"
	11 "Bitte geben Sie einen Allianz-Tag mit 3-4 Zeichen ein"
	12 "Bitte verwenden Sie keine Sonderzeichen"
	13 "Bitte geben Sie einen 3-15 Zeichen langen Benutzernamen ein"
)
"vietnamese" (dict
	1 "Không có liên minh? Gõ \"skip\""
	2 "Tuyệt vời! <@!> Bạn vừa nhận được Thẻ máy chủ của mình! Bây giờ hãy chuyển sang <#> <1/5>"
	3 "<@!> Nhập thẻ liên minh của bạn vào đây <2/5>"
	4 "Cái này hay đấy! <@!> bạn hiện có Thẻ Liên minh! Tiếp tục và tiến tới <#> <2/5>"
	5 "<@!> nhập Tên trò chơi nhân vật của bạn vào đây! <3/5>"
	6 "Hoàn hảo! <@!> bạn đã cập nhật tên hiển thị thành Tên trò chơi nhân vật của mình! Hai bước nữa, tiến tới <#> <3/5>"
	7 "<@!> chọn thứ hạng liên minh trong trò chơi của bạn <4/5>"
	8 "Không thể thêm phản ứng cho người dùng đã chặn bot. Đã cập nhật biệt hiệu"
	9 "Vui lòng nhập thẻ 3-4 chữ số"
	10 "Vui lòng nhập thẻ số"
	11 "Vui lòng nhập thẻ liên minh 3-4 ký tự"
	12 "Vui lòng không sử dụng ký tự đặc biệt"
	13 "Vui lòng nhập tên người dùng 3-15 ký tự"
)
"japanese" (dict
	1 "同盟はありませんか？ \"skip\" ップ」と入力してください"
	2 " 素晴らしい！ <@!> サーバー タグを受け取りました。 <#> に進みます <1/5>"
	3 "<@!> ここに同盟タグを入力してください <2/5>"
	4 "これはカッコいい！ <@!> さんは同盟タグを獲得しました! 続行して <#> に進みます <2/5>"
	5 "<@!> ここにキャラクター ゲーム名を入力してください! <3/5>"
	6 "完璧！ <@!> 表示名をキャラクター ゲーム名に更新しました! さらに 2 つの手順を実行して、<#> に進みます <3/5>"
	7 "<@!> はゲーム内の同盟ランクを選択します <4/5>"
	8 "ボットをブロックしたユーザーにリアクションを追加することはできません。 ニックネームを更新しました"
	9 "3-4桁のタグを入力してください"
	10 "数字タグを入力してください"
	11 "3-4文字の同盟タグを入力してください"
	12 "特殊文字は使用しないでください"
	13 "3-15 文字のユーザー名を入力してください"
)
"turkish" (dict
	1 "İttifak yok mu? \"skip\" yazın"
	2 "Mükemmel! <@!> Sunucu Etiketinizi yeni aldınız! Şimdi <#>'a ilerleyin <1/5>"
	3 "<@!> İttifak etiketinizi buraya girin <2/5>"
	4 "Bu havalı! <@!> artık bir İttifak Etiketine sahipsiniz! Devam edin ve <#>'a ilerleyin <2/5>"
	5 "<@!> Karakter Oyunu Adınızı buraya yazın! <3/5>"
	6 "Mükemmel! <@!>, görünen adınızı Karakter Oyunu Adınızla güncellediniz! İki adım daha, <#>'a ilerleyin <3/5>"
	7 "<@!> oyun içi ittifak rütbenizi seçin <4/5>"
	8 "Botu engelleyen kullanıcıya tepki eklenemez. Takma ad güncellendi"
	9 "Lütfen 3-4 haneli bir etiket girin"
	10 "Lütfen sayısal bir etiket girin"
	11 "Lütfen 3-4 karakterlik bir ittifak etiketi girin"
	12 "Lütfen özel karakterler kullanmayın"
	13 "Lütfen 3-15 karakterlik bir kullanıcı adı girin"
)
}}
{{dbSet 0 "languageDB" $languages}}