{{$languages := sdict
"english" (dict
	1 "No alliance? Type \"skip\""
	2 "Awesome! <@!> You've just received your Server Tag! Now proceed to <#> <1/5>"
	3 "<@!> Enter your alliance tag here <2/5>"
	4 "This is cool! <@!> you now have an Alliance Tag! Continue and proceed to <#> <2/5>"
	5 "<@!> type your Character Game Name over here! <3/5>"
	6 "Perfect! <@!> you've updated your display name to your Character Game Name! Two more steps, proceed to <#> <3/5>"
	7 "<@!> select your in-game alliance rank <4/5>"
	8 "Cannot add reaction to user who has blocked bot. Nickname updated"
	9 "Please input a 3-4 digit tag"
	10 "Please input a numeric tag"
	11 "Please input a 3-4 character alliance tag"
	12 "Please don't use special characters"
	13 "Please input a 3-15 character username"
	14 "Let's get started <@!>, proceed to <#> <0/5>"
	15 "Alright <@!>, let's get you ready to be onboarded and verified!"
	16 "Here you go <@!>, we just got started! <0/5>"
	17 "Finally!! <@!> You are here!! Final step to the other side!! <5/5>"
	18 "Hahaha! You made it! <@!> Welcome to the other side!"
	19 "Well done! <@!> now get ready for the final step⁠ <#> <5/5>"
	20 "Hello there warrior! 🤺 \n\n**<@!> Thank you for joining, please proceed to get onboarded and verified.**  ✅\n\n- You will now be guided with the codings of <@!765316548516380732> to get onboarded and verified through the following steps:\n 1 - 🚩 Server Tag : Type your server number.\n 2 - 🏰 Alliance Tag : Type your Alliance Tag.\n 3 - 🎮 Game Name : Type your Game Name.\n 4 - 🌟 Alliance Rank : Select your Alliance Rank.\n 5 - 📃 Discord Rules : Read and Verify.\n\n> - This will take less than a minute, please follow the instructions of the bot. \n\n⚠️You can only select **ONE Language**, if you selected two languages, the bot will respond to you with the last selected language, to adjust and fix, go back to <#L> ⚠️ \n\n> 💥 **HINT: This message is customised based on the language you last selected** 💥\n\n### **We are waiting for you on the other side!** 🌀 \n\n### **React with a ✅  to proceed and get started.**\n## 👉 <#S>"
)
"spanish" (dict
	1 "¿Sin alianza? Escribe \"skip\""
	2 "¡Impresionante! <@!> ¡Acabas de recibir tu etiqueta de servidor! Ahora procede a <#> <1/5>"
	3 "<@!> Introduce tu etiqueta de alianza aquí <2/5>"
	4 "¡Esto es genial! <@!> ¡ahora tienes una etiqueta de alianza! Continúe y pase a <#> <2/5>"
	5 "<@!> ¡escribe el nombre del juego de tu personaje aquí! <3/5>"
	6 "¡Perfecto! <@!> ¡Has actualizado tu nombre para mostrar al nombre del juego de tu personaje! Dos pasos más, continúa con <#> <3/5>"
	7 "<@!> selecciona tu rango de alianza en el juego <4/5>"
	8 "No se puede agregar una reacción al usuario que ha bloqueado el bot. Apodo actualizado"
	9 "Ingrese una etiqueta de 3 a 4 dígitos"
	10 "Ingrese una etiqueta numérica"
	11 "Ingrese una etiqueta de alianza de 3-4 caracteres"
	12 "Por favor no utilices caracteres especiales"
	13 "Ingrese un nombre de usuario de 3 a 15 caracteres"
	14 "Comencemos <@!>, continúe con <#> <0/5>"
	15 "Muy bien <@!>, ¡vamos a prepararte para ser incorporado y verificado!"
	16 "Aquí tienes <@!>, ¡acabamos de empezar! <0/5>"
	17 "¡¡Finalmente!! <@!> ¡¡Estás aquí!! ¡¡Último paso al otro lado!! <5/5>"
	18 "¡Jajaja! ¡Lo hiciste! <@!> ¡Bienvenido al otro lado!"
	19 "¡Bien hecho! <@!> ahora prepárate para el paso final⁠ <#> <5/5>"
	20 "¡Hola guerrero! 🤺 \n\n**<@!> Gracias por unirte, continúa con la incorporación y la verificación.** ✅\n\n- Ahora se le guiará con las codificaciones de <@!765316548516380732> para incorporarse y verificarse mediante los siguientes pasos:\n 1 - 🚩 Etiqueta de servidor: escriba su número de servidor.\n 2 - 🏰 Etiqueta de Alianza: Escribe tu Etiqueta de Alianza.\n 3 - 🎮 Nombre del juego: escribe el nombre del juego.\n 4 - 🌟 Rango de alianza: seleccione su rango de alianza.\n 5 - 📃 Reglas de Discord: Leer y verificar.\n\n> - Esto tomará menos de un minuto, siga las instrucciones del bot.\n\n⚠️Solo puedes seleccionar **UN Idioma**, si seleccionaste dos idiomas, el bot te responderá con el último idioma seleccionado, para ajustar y arreglar regresa a <#L> ⚠️\n\n> 💥 **SUGERENCIA: Este mensaje se personaliza según el último idioma que seleccionó** 💥\n\n### **¡Te esperamos del otro lado!** 🌀\n\n### **Reacciona con un ✅ para continuar y comenzar.**\n## 👉 <#S>"
)
"french" (dict
	1 "Pas d'alliance ? Tapez \"skip\""
	2 "Génial! <@!> Vous venez de recevoir votre Server Tag ! Passez maintenant à <#> <1/5>"
	3 "<@!> Entrez votre tag d'alliance ici <2/5>"
	4 "C'est cool! <@!> vous avez maintenant un tag Alliance ! Continuez et passez à <#> <2/5>"
	5 "<@!> tapez le nom de votre jeu de personnage ici ! <3/5>"
	6 "Parfait! <@!> vous avez mis à jour votre nom d'affichage avec le nom de votre jeu de personnage ! Deux étapes supplémentaires, passez à <#> <3/5>"
	7 "<@!> sélectiQonnez votre rang d'alliance dans le jeu <4/5>"
	8 "Impossible d'ajouter une réaction à l'utilisateur qui a bloqué le bot. Pseudonyme mis à jour"
	9 "Veuillez saisir une balise à 3-4 chiffres"
	10 "Veuillez saisir une balise numérique"
	11 "Veuillez saisir une balise d'alliance de 3 à 4 caractères"
	12 "Merci de ne pas utiliser de caractères spéciaux"
	13 "Veuillez saisir un nom d'utilisateur de 3 à 15 caractères"
	14 "Commençons <@!>, passez à <#> <0/5>"
	15 "Très bien <@!>, préparons-nous à être intégré et vérifié !"
	16 "Et voilà <@!>, nous venons tout juste de commencer ! <0/5>"
	17 "Enfin!! <@!> Vous êtes ici !! Dernière étape vers l'autre côté !! <5/5>"
	18 "Hahaha! Tu l'as fait! <@!> Bienvenue de l'autre côté !"
	19 "Bien joué! <@!> préparez-vous maintenant pour la dernière étape⁠ <#> <5/5>"
	20 "Bonjour guerrier ! 🤺\n\n**<@!> Merci de votre participation, veuillez procéder pour vous inscrire et vérifier.** ✅\n\n- Vous serez maintenant guidé avec les codages de <@!765316548516380732> pour être intégré et vérifié à travers les étapes suivantes :\n 1 - 🚩 Server Tag : Saisissez votre numéro de serveur.\n 2 - 🏰 Tag Alliance : Tapez votre Tag Alliance.\n 3 - 🎮 Nom du jeu : Tapez votre nom de jeu.\n 4 - 🌟 Rang Alliance : Sélectionnez votre Rang Alliance.\n 5 - 📃 Règles Discord : Lisez et vérifiez.\n\n> - Cela prendra moins d'une minute, veuillez suivre les instructions du bot.\n\n⚠️Vous ne pouvez sélectionner **UNE langue**, si vous avez sélectionné deux langues, le bot vous répondra avec la dernière langue sélectionnée, pour ajuster et corriger, revenez à <#L> ⚠️\n\n> 💥 **ASTUCE : Ce message est personnalisé en fonction de la langue que vous avez sélectionnée en dernier** 💥\n\n### **On vous attend de l'autre côté !** 🌀\n\n### **Réagissez avec un ✅ pour continuer et commencer.**\n## 👉 <#S>"
)
"russian" (dict
	1 "Нет союза? Напишите \"skip\""
	2 "Потрясающий! <@!> Вы только что получили тег сервера! Теперь перейдите к <#> <1/5>"
	3 "<@!> Введите здесь тег вашего альянса <2/5>"
	4 "Это здорово! <@!> теперь у вас есть тег альянса! Продолжайте и перейдите к <#> <2/5>"
	5 "<@!> введите здесь свое игровое имя персонажа! <3/5>"
	6 "Идеальный! <@!> вы обновили отображаемое имя на игровое имя вашего персонажа! Еще два шага, переходим к <#> <3/5>"
	7 "<@!> выберите свой внутриигровой рейтинг альянса <4/5>"
	8 "Невозможно добавить реакцию на пользователя, заблокировавшего бота. Псевдоним обновлен"
	9 "Введите тег из 3-4 цифр"
	10 "Пожалуйста, введите числовой тег"
	11 "Введите тег альянса из 3-4 символов"
	12 "Пожалуйста, не используйте специальные символы"
	13 "Пожалуйста, введите имя пользователя длиной от 3 до 15 символов"
	14 "Давайте начнем <@!>, перейдите к <#> <0/5>"
	15 "Хорошо, <@!>, подготовим тебя к регистрации и проверке!"
	16 "Держи <@!>, мы только начали! <0/5>"
	17 "Окончательно!! <@!> Ты здесь!! Последний шаг на другую сторону!! <5/5>"
	18 "Ха-ха-ха! Ты сделал это! <@!> Добро пожаловать на другую сторону"
	19 "Отличная работа! <@!> теперь приготовьтесь к последнему шагу⁠ <#> <5/5>"
	20 "Привет, воин! 🤺\n\n**<@!> Спасибо, что присоединились, пожалуйста, приступайте к регистрации и проверке.** ✅\n\n- Теперь вам будут предложены коды <@!765316548516380732> для регистрации и проверки, выполнив следующие шаги:\n 1 — 🚩 Тег сервера: введите номер своего сервера.\n 2 — 🏰 Тег альянса: введите тег вашего альянса.\n 3 — 🎮 Название игры: введите название игры.\n 4 — 🌟 Ранг Альянса: выберите свой ранг Альянса.\n 5 — 📃 Правила Discord: прочитайте и проверьте.\n\n> - Это займет меньше минуты, следуйте инструкциям бота.\n\n⚠️Вы можете выбрать только **ОДИН язык**. Если вы выбрали два языка, бот ответит вам на последнем выбранном языке. Для настройки и исправления вернитесь к <#L> ⚠️\n\n> 💥 **СОВЕТ: это сообщение настроено на основе последнего выбранного вами языка** 💥\n\n### **Мы ждём тебя на той стороне!** 🌀\n\n### **Отреагируйте, нажав ✅, чтобы продолжить и начать работу.**\n## 👉 <#S>"
)
"chinese" (dict
	1 "没有联盟? 输入 \"skip\""
	2 "惊人的! <@!> 您刚刚收到您的服务器标签! 现在前往 <#> <1/5>"
	3 "<@!> 在此输入您的联盟标签 <2/5>"
	4 "这很酷! <@!> 您现在拥有联盟标签! 继续并前往<#> <2/5>"
	5 "<@!> 在这里输入您的角色游戏名称! <3/5>"
	6 "完美的! <@!> 您已将您的显示名称更新为您的角色游戏名称! 再执行两步，继续 <#>! <3/5>"
	7 "<@!> 选择您的游戏内联盟等级 <4/5>"
	8 "无法向阻止机器人的用户添加反应. 昵称已更新"
	9 "请输入3-4位标签"
	10 "请输入数字标签"
	11 "请输入3-4个字符的联盟标签"
	12 "请不要使用特殊字符"
	13 "请输入3-15个字符的用户名"
	14 "让我们开始吧 <@!>，继续 <#> <0/5>"
	15 "好的 <@!>，让我们为您准备好加入和验证！"
	16 "给你 <@!>，我们才刚刚开始！ <0/5>"
	17 "最后！! <@!> 你在这里！！最后一步到另一边！ <5/5>"
	18 "哈哈哈! 你做到了！ <@!> 欢迎来到另一边！"
	19 "做得好! <@!> 现在准备好最后一步⁠ <#> <5/5>"
	20 "你好，战士！ 🤺\n\n**<@!> 感谢您的加入，请继续加入并验证。** ✅\n\n- 现在将引导您使用 <@!765316548516380732> 的编码进行注册并通过以下步骤进行验证：\n 1 - 🚩 服务器标签：输入您的服务器编号。\n 2 - 🏰 联盟标签：输入您的联盟标签。\n 3 - 🎮 游戏名称：输入您的游戏名称。\n 4 - 🌟 联盟排名：选择您的联盟排名。\n 5 - 📃 不和谐规则：阅读并验证。\n\n> - 这将需要不到一分钟的时间，请按照机器人的说明进行操作。\n\n⚠️您只能选择**一种语言**，如果您选择了两种语言，机器人会用最后选择的语言回复您，要调整和修复，请返回<#L> ⚠️\n\n> 💥 **提示：此消息是根据您上次选择的语言定制的** 💥\n\n### **我们在另一边等你！** 🌀\n\n### **用 ✅ 进行反应以继续并开始。**\n## 👉 <#S>"
)
}}
{{dbSet 0 "languageDB" $languages}}